abbain<N-o>
abbassament<N-o>
abbonament<N-o>
abbondanz<N-a>
abbuon<N-o>
abdicaz<N-ione>
abiez<N-ione>
abili<N-tA>
abiss<N-o>
abitabili<N-tA>
abitacol<N-o>
abitin<N-o>
abitudin<N-e>
abnegaz<N-ione>
aboliz<N-ione>
abortis<N-ta>
abruzzes<N-e>
abusivism<N-o>
abusiv<N-o>
abus<N-o>
accademic<N-o>
accaniment<N-o>
accendin<N-o>
accent<N-o>
accerchiament<N-o>
acciacc<N-o>
acciaieri<N-a>
accoglienz<N-a>
accompagnament<N-o>
accompagnatric<N-e>
accondiscendenz<N-a>
accont<N-o>
accord<N-o>
accorgiment<N-o>
accortezz<N-a>
accostament<N-o>
accozzagli<N-a>
accumulator<N-e>
accuratezz<N-a>
accusator<N-e>
acid<N-o>
acin<N-o>
acm<N-e>
acqu<N-a>
acquazzon<N-e>
acquedott<N-o>
acquerell<N-o>
acquiescenz<N-a>
acquirent<N-e>
acredin<N-e>
acroba<N-ta>
acrobazi<N-a>
acronim<N-o>
addebit<N-o>
addensament<N-o>
addestrator<N-e>
addet<N-ta>
addobb<N-o>
adduttor<N-e>
adeguament<N-o>
adep<N-ta>
ades<N-ione>
adesiv<N-o>
adolescenz<N-a>
adorat<N-o>
adoz<N-ione>
aeronautic<N-a>
aeroplanin<N-o>
aeroplan<N-o>
aeroport<N-o>
aeroportual<N-e>
afasi<N-a>
affabili<N-tA>
affar<N-e>
affarucc<N-io>
affettuosi<N-tA>
affiatament<N-o>
affid<N-o>
affiliaz<N-ione>
affiorament<N-o>
affitt<N-o>
affluss<N-o>
affollament<N-o>
affossament<N-o>
affossator<N-e>
affront<N-o>
afghan<N-o>
aforis<N-ma>
african<N-o>
afro-american<N-o>
afror<N-e>
agap<N-e>
agendin<N-a>
agent<N-e>
agganc<N-io>
aggegg<N-io>
aggettivaz<N-ione>
aggiudicaz<N-ione>
aggiun<N-ta>
aggiustament<N-o>
agglomeraz<N-ione>
aggressor<N-e>
ag<N-io>
agiografi<N-a>
agitaz<N-ione>
agnell<N-o>
ag<N-o>
agonism<N-o>
agonis<N-ta>
agrar<N-io>
agriturism<N-o>
agrumet<N-o>
aiol<N-a>
aiuol<N-a>
aiutant<N-e>
alb<N-a>
alberell<N-o>
albergator<N-e>
alberghier<N-a>
albergon<N-e>
albicocc<N-a>
alb<N-o>
alcol<N-non>
alcolizzat<N-o>
alet<N-ta>
alfabet<N-o>
alfis<N-ta>
alg<N-a>
algerin<N-a>
algoritm<N-o>
alien<N-o>
alit<N-o>
alleat<N-o>
allegat<N-o>
allegr<N-a>
allegri<N-a>
allenament<N-o>
aller<N-gia>
allevament<N-o>
alliev<N-a>
alligator<N-e>
allineament<N-o>
allitteraz<N-ione>
allocaz<N-ione>
allocuz<N-ione>
allontanament<N-o>
alluc<N-e>
alluv<N-ione>
alt<N-non>
alter<N-a>
alteri<N-tA>
alternanz<N-a>
alternativ<N-o>
altur<N-a>
alunn<N-a>
alvear<N-e>
alzator<N-e>
amalga<N-ma>
amarcord<N-non>
amar<N-o>
amator<N-e>
ambasceri<N-a>
ambascia<N-ta>
ambasciatric<N-e>
ambientalis<N-ta>
ambigui<N-tA>
ambit<N-o>
ambivalenz<N-a>
ambiz<N-ione>
amb<N-o>
ameni<N-tA>
amic<N-a>
aminoacid<N-o>
ammanc<N-o>
amministrativ<N-a>
ammiragli<N-a>
ammiratric<N-e>
ammissibili<N-tA>
ammodernament<N-o>
ammoniment<N-o>
ammutinat<N-o>
amnesi<N-a>
amorazz<N-o>
amorin<N-o>
ampless<N-o>
ampliament<N-o>
amplificaz<N-ione>
ampoll<N-a>
anabolizzant<N-e>
anagraf<N-e>
analfabe<N-ta>
analfabetism<N-o>
analis<N-ta>
analo<N-gia>
ananas<N-non>
anarchi<N-a>
anarchic<N-o>
anatomi<N-a>
anatomopatolog<N-o>
anatroccol<N-o>
anchorman<N-non>
ancoragg<N-io>
andalus<N-o>
andatur<N-a>
andazz<N-o>
andirivien<N-i>
andron<N-e>
aneddot<N-o>
anestesi<N-a>
anfetamin<N-a>
anfiteatr<N-o>
angheri<N-a>
angiport<N-o>
anglican<N-o>
anglicism<N-o>
anglis<N-ta>
anglofil<N-o>
anglosasson<N-e>
angolan<N-o>
angolaz<N-ione>
anguill<N-a>
anguri<N-a>
ani<N-ma>
animal<N-e>
animalis<N-ta>
animator<N-e>
animatric<N-e>
anim<N-o>
animosi<N-tA>
annacquament<N-o>
annegat<N-o>
annett<N-o>
annuali<N-tA>
annullament<N-o>
annuvolament<N-o>
an<N-o>
anonim<N-o>
anoressi<N-a>
anoressic<N-o>
anormali<N-tA>
antecedent<N-e>
antiabortis<N-ta>
antibiotic<N-o>
anticagli<N-a>
anticamer<N-a>
anticipator<N-e>
anticipaz<N-ione>
anticomunism<N-o>
anticoncezional<N-e>
anticorp<N-o>
antiero<N-e>
antifascism<N-o>
antifascis<N-ta>
antifurt<N-o>
antinomi<N-a>
antipod<N-e>
antiproibizionis<N-ta>
antisemi<N-ta>
antisemitism<N-o>
antiterrorism<N-o>
antites<N-i>
antitrust<N-non>
apati<N-a>
apic<N-e>
apocrif<N-o>
apologe<N-ta>
apolog<N-o>
apori<N-a>
apoteos<N-i>
appannagg<N-io>
appannament<N-o>
apparat<N-o>
apparecchiett<N-o>
appariz<N-ione>
appartament<N-o>
appartenent<N-e>
appassionat<N-o>
appellativ<N-o>
appetit<N-o>
appettit<N-o>
appostament<N-o>
apprendiment<N-o>
apprendistat<N-o>
apprezzament<N-o>
approcc<N-io>
approd<N-o>
appropriaz<N-ione>
approvaz<N-ione>
apripis<N-ta>
aquilon<N-e>
aran<N-cia>
arancia<N-ta>
aratr<N-o>
arbitr<N-o>
arcaic<N-o>
arcangel<N-o>
arcan<N-o>
arca<N-ta>
architett<N-o>
architrav<N-e>
archiviaz<N-ione>
archiv<N-io>
archivis<N-ta>
arcier<N-e>
arcinemic<N-o>
arc<N-o>
arditezz<N-a>
ardit<N-o>
aren<N-a>
argan<N-o>
argenteri<N-a>
argentin<N-a>
argin<N-e>
argomentaz<N-ione>
arguzi<N-a>
ari<N-a>
aridi<N-tA>
aristocratic<N-o>
arlecchin<N-o>
ar<N-ma>
armadiett<N-o>
armamentar<N-io>
armament<N-o>
armat<N-o>
armen<N-a>
armeri<N-a>
armier<N-e>
arnes<N-e>
arp<N-a>
arp<N-ione>
arrampicator<N-e>
arredament<N-o>
arretrament<N-o>
arricchiment<N-o>
arrivis<N-ta>
arroccament<N-o>
arrossament<N-o>
arruolament<N-o>
artefic<N-e>
artier<N-e>
artificier<N-e>
artiglieri<N-a>
artigl<N-io>
art<N-o>
artros<N-i>
ascendent<N-e>
ascens<N-ione>
asces<N-a>
asciugaman<N-o>
asciuttezz<N-a>
ascolt<N-o>
asfissiant<N-e>
asimmetri<N-a>
asin<N-o>
asol<N-a>
asparag<N-o>
aspett<N-o>
aspirant<N-e>
asportaz<N-ione>
assaltator<N-e>
assalt<N-o>
assassin<N-a>
assed<N-io>
assemble<N-a>
assent<N-e>
assenteism<N-o>
assert<N-o>
assertor<N-e>
asserz<N-ione>
assessorat<N-o>
assis<N-e>
assistenz<N-a>
assistenzialism<N-o>
ass<N-o>
associa<N-ta>
assol<N-o>
assolutism<N-o>
assoluz<N-ione>
assorbent<N-e>
assortiment<N-o>
assunt<N-o>
assurdi<N-tA>
assurd<N-o>
as<N-ta>
astant<N-e>
asterisc<N-o>
astrofisic<N-o>
astrolog<N-a>
astrolog<N-o>
astut<N-o>
ate<N-o>
atipic<N-o>
atmosfer<N-a>
atoll<N-o>
atom<N-o>
atout<N-non>
atroci<N-tA>
attaccant<N-e>
attendent<N-e>
attentat<N-o>
attentator<N-e>
attent<N-o>
attenuant<N-e>
attenuaz<N-ione>
attitudin<N-e>
attoni<N-ta>
attrattiv<N-a>
attribuz<N-ione>
attuali<N-tA>
audac<N-e>
audienc<N-e>
audiovisiv<N-o>
auditorium<N-non>
audiz<N-ione>
aument<N-o>
aureol<N-a>
auror<N-a>
auspic<N-io>
austeri<N-tA>
australian<N-o>
autentici<N-tA>
autoadesiv<N-o>
autoanalis<N-i>
autoblind<N-o>
autobomb<N-a>
autocarr<N-o>
autocelebraz<N-ione>
autocitaz<N-ione>
autocrazi<N-a>
autodenun<N-cia>
autodrom<N-o>
autoferrotranvier<N-e>
autogovern<N-o>
autoironi<N-a>
auto<N-ma>
automatic<N-a>
automaz<N-ione>
automezz<N-o>
automobil<N-e>
automobilis<N-ta>
autonomi<N-a>
autonom<N-o>
autoparc<N-o>
autoproduttor<N-e>
autor<N-e>
autorifor<N-ma>
autorimess<N-a>
autoritar<N-io>
autori<N-tA>
autorizzaz<N-ione>
autosalon<N-e>
autoscuol<N-a>
autostrad<N-a>
autotrasportator<N-e>
autotren<N-o>
avall<N-o>
avampost<N-o>
avanguardi<N-a>
avanguardism<N-o>
avanspettacol<N-o>
avanzament<N-o>
avari<N-a>
aver<N-e>
av<N-o>
avvelenator<N-e>
avvenir<N-e>
avvent<N-o>
avventor<N-e>
avventur<N-a>
avventurier<N-o>
avventurism<N-o>
avverb<N-io>
avversari<N-a>
avvers<N-ione>
avvertiment<N-o>
avviament<N-o>
avvicinament<N-o>
avviliment<N-o>
avvisagli<N-a>
avvocat<N-o>
avvolgiment<N-o>
avvolto<N-io>
azale<N-a>
aziendin<N-a>
azzerament<N-o>
azzurrin<N-o>
babbe<N-o>
babbuin<N-o>
babel<N-e>
baby<N-non>
baby-boom<N-non>
baby-calciator<N-e>
baby-killer<N-non>
baccan<N-o>
bacchetton<N-e>
bacett<N-o>
bachec<N-a>
bacill<N-o>
bacinell<N-a>
bac<N-o>
baffon<N-e>
bagaglia<N-io>
bagarinagg<N-io>
baggiana<N-ta>
baglior<N-e>
bagnant<N-e>
bailamm<N-e>
baionet<N-ta>
bai<N-ta>
balbettament<N-o>
balcona<N-ta>
baldacchin<N-o>
balen<N-a>
bali<N-a>
ball<N-a>
ballato<N-io>
ballerin<N-o>
ballett<N-o>
ball<N-o>
ballottagg<N-io>
balneaz<N-ione>
balord<N-o>
baltic<N-o>
balzell<N-o>
bambinacc<N-io>
bambinai<N-a>
bambin<N-o>
bambinon<N-e>
bambolon<N-a>
banan<N-a>
banan<N-o>
banca-dat<N-i>
bancarell<N-a>
bancarottier<N-e>
banchett<N-o>
band<N-a>
bandan<N-a>
banditor<N-e>
band<N-o>
bar<N-non>
baracc<N-a>
baracchet<N-ta>
baraccona<N-ta>
barattol<N-o>
barbar<N-a>
barbari<N-e>
barbarism<N-o>
barbar<N-o>
barbier<N-e>
barc<N-a>
barchin<N-o>
barell<N-a>
bares<N-e>
baril<N-e>
baris<N-ta>
bariton<N-o>
bar<N-o>
barometr<N-o>
baroness<N-a>
baronett<N-o>
baroni<N-a>
barrag<N-e>
barret<N-ta>
barrica<N-ta>
barrier<N-a>
barzellet<N-ta>
basament<N-o>
baset<N-ta>
basilic<N-a>
basket<N-non>
bassezz<N-a>
bassoriliev<N-o>
bassur<N-a>
bastard<N-o>
bastona<N-ta>
baston<N-e>
batav<N-o>
battagli<N-a>
battent<N-e>
batter<N-io>
battesim<N-o>
batticuor<N-e>
battis<N-ta>
battistrad<N-a>
battutac<N-cia>
battutin<N-a>
batuffol<N-o>
baul<N-e>
bav<N-a>
baver<N-o>
bazar<N-non>
bazzecol<N-a>
beat<N-o>
bebé<N-non>
becchin<N-o>
belcant<N-o>
bellezz<N-a>
bellimbust<N-o>
bellunes<N-e>
belluri<N-a>
bel<N-tA>
benedet<N-ta>
benediz<N-ione>
beneficiari<N-a>
benemerenz<N-a>
beneplacit<N-o>
benesser<N-e>
benestant<N-e>
beneventan<N-o>
bengales<N-e>
benservit<N-o>
bergamasc<N-a>
berret<N-ta>
bersaglier<N-e>
bersagl<N-io>
best-seller<N-non>
bestemmi<N-a>
bestemmiator<N-e>
bestiali<N-tA>
bestiar<N-io>
bestseller<N-non>
betonier<N-a>
bettol<N-a>
bevand<N-a>
beveron<N-e>
bianc<N-a>
biancazzurr<N-o>
biancheri<N-a>
biancocelest<N-e>
biancoross<N-o>
biathlon<N-non>
bibi<N-ta>
bibliotec<N-a>
bibliotecar<N-io>
bicameral<N-e>
bicchierin<N-o>
bic<N-i>
bicilindric<N-a>
bidell<N-a>
bidet<N-non>
biec<N-o>
bieloruss<N-o>
biennal<N-e>
biglietta<N-io>
biglietteri<N-a>
bigliett<N-o>
bikin<N-i>
bilan<N-cia>
bilancin<N-o>
bilinguism<N-o>
bilocal<N-e>
bimb<N-a>
bimbett<N-o>
bimb<N-o>
binocol<N-o>
binom<N-io>
biograf<N-o>
biolog<N-a>
biolo<N-gia>
biolog<N-o>
biomeccanic<N-o>
biond<N-a>
biosfer<N-a>
biossid<N-o>
bip<N-non>
bireattor<N-e>
birichin<N-o>
birr<N-a>
birra<N-io>
birreri<N-a>
bisbigl<N-io>
bischer<N-o>
biscott<N-o>
bistrot<N-non>
bit<N-non>
bivacc<N-o>
biv<N-io>
bla-bl<N-a>
blackout<N-non>
blasona<N-ta>
blason<N-e>
blat<N-ta>
blazer<N-non>
blindatur<N-a>
blitz<N-non>
blob<N-non>
blocchett<N-o>
bluesman<N-non>
blus<N-a>
bo<N-a>
bobin<N-a>
boccascen<N-a>
bocchin<N-o>
boccol<N-o>
boccon<N-e>
bohèm<N-e>
boler<N-o>
boll<N-a>
bollet<N-ta>
bollicin<N-a>
bollin<N-o>
bollitor<N-e>
bomb<N-a>
bombarol<N-o>
bombol<N-a>
bond<N-non>
bonific<N-o>
bonsa<N-i>
book<N-non>
boom<N-non>
bor<N-a>
borbott<N-io>
borda<N-ta>
bordell<N-o>
bord<N-o>
borghes<N-e>
borg<N-o>
borgognon<N-e>
borgomastr<N-o>
bori<N-a>
borrac<N-cia>
bors<N-a>
borsaiol<N-o>
borsar<N-o>
borseggiator<N-e>
boscaiol<N-o>
boschett<N-o>
bosc<N-o>
bosniac<N-a>
bosniac<N-o>
boss<N-o>
bossol<N-o>
botanic<N-a>
botanic<N-o>
botol<N-a>
bott<N-e>
botteghin<N-o>
botteguc<N-cia>
bott<N-o>
bottoncin<N-o>
bouquet<N-non>
box<N-non>
boy<N-non>
boy-scout<N-non>
bozz<N-a>
braccial<N-e>
bracciant<N-e>
braccia<N-ta>
bracc<N-io>
bracconier<N-e>
bracier<N-e>
bramin<N-o>
bramosi<N-a>
branc<N-a>
branchi<N-a>
brand<N-a>
brandell<N-o>
brav<N-a>
brava<N-ta>
bravur<N-a>
break<N-non>
brescian<N-o>
brevettabili<N-tA>
bricolag<N-e>
bridg<N-e>
briefing<N-non>
brigadier<N-e>
brigantagg<N-io>
brigli<N-a>
brillantin<N-a>
br<N-io>
brioch<N-e>
briscol<N-a>
britann<N-o>
brocc<N-a>
brocc<N-o>
brochur<N-e>
brogliacc<N-io>
brogl<N-io>
broker<N-non>
brokeragg<N-io>
bronc<N-io>
broncopneumopati<N-a>
brontol<N-io>
brontolon<N-e>
bronz<N-o>
browser<N-non>
bruciat<N-o>
bruciatur<N-a>
brughier<N-a>
bru<N-ma>
brusc<N-a>
brusì<N-o>
bruttin<N-a>
brutt<N-o>
buc<N-a>
budell<N-o>
budget<N-non>
budin<N-o>
bufal<N-o>
buffon<N-e>
bu<N-gia>
bulgar<N-a>
bulldozer<N-non>
bund<N-non>
buonafed<N-e>
buonism<N-o>
buon<N-o>
buonsens<N-o>
burattina<N-io>
burattin<N-o>
burin<N-o>
burl<N-a>
burocrat<N-e>
burocrates<N-e>
burocratism<N-o>
burocrazi<N-a>
burr<N-o>
businessman<N-non>
bussol<N-a>
busta-pag<N-a>
bustarell<N-a>
bustin<N-a>
bustin<N-o>
bust<N-o>
buvett<N-e>
by-pass<N-non>
cabal<N-a>
cabalis<N-ta>
cabaret<N-non>
cabarettis<N-ta>
cabriolet<N-non>
cac<N-cia>
caccia-bombardier<N-e>
cacciabombardier<N-e>
cacciamin<N-e>
cacciatorpedinier<N-e>
cacicc<N-o>
cac<N-o>
cactus<N-non>
cadaverin<N-o>
caduci<N-tA>
cadu<N-ta>
cafon<N-e>
cafè<N-non>
cagliaritan<N-o>
cagn<N-a>
cagnet<N-ta>
cagnolin<N-o>
cagnon<N-e>
calabron<N-e>
calc<N-e>
calcestruzz<N-o>
calciatric<N-e>
calciomercat<N-o>
calc<N-ione>
calc<N-o>
calcolator<N-e>
calderon<N-e>
calendar<N-io>
calet<N-ta>
call<N-e>
calligrafi<N-a>
calmier<N-e>
calm<N-o>
calorifer<N-o>
calunni<N-a>
calur<N-a>
calvinis<N-ta>
calvizi<N-e>
calzamagli<N-a>
camaleont<N-e>
cambiament<N-o>
cambiavalut<N-e>
camb<N-io>
cambogian<N-o>
camer<N-a>
cameraman<N-non>
cameramen<N-non>
camera<N-ta>
cameratism<N-o>
camerin<N-o>
camerunens<N-e>
cami<N-cia>
camionet<N-ta>
cammellier<N-e>
cammell<N-o>
camminament<N-o>
cammin<N-o>
camomill<N-a>
campan<N-a>
campanell<N-a>
campanellin<N-o>
campanell<N-o>
campa<N-ta>
campeggiator<N-e>
campegg<N-io>
camper<N-non>
campett<N-o>
campiell<N-o>
campionament<N-o>
campionat<N-o>
campionatur<N-a>
campioncin<N-o>
camposant<N-o>
camuffament<N-o>
can-can<N-non>
canaglia<N-ta>
canal<N-e>
canalin<N-a>
canalon<N-e>
canap<N-o>
cancellaz<N-ione>
cancelleri<N-a>
cancellierat<N-o>
cancerogen<N-o>
candel<N-a>
candelin<N-a>
candelott<N-o>
candidat<N-o>
candor<N-e>
can<N-e>
canin<N-o>
cannocchial<N-e>
cannoncin<N-o>
cannon<N-e>
cannonier<N-a>
cannul<N-a>
canonic<N-a>
canot<N-ta>
canottagg<N-io>
canottier<N-a>
canottier<N-e>
canott<N-o>
cantabili<N-tA>
cantastori<N-e>
canta<N-ta>
cantautor<N-e>
cantic<N-a>
cantier<N-e>
cantin<N-a>
canzoncin<N-a>
canzon<N-e>
cap<N-a>
capann<N-a>
capannell<N-o>
capann<N-o>
caparb<N-io>
caparr<N-a>
capataz<N-non>
capatin<N-a>
capell<N-o>
capett<N-o>
capezzol<N-o>
capillari<N-tA>
capitalin<N-a>
capitalis<N-ta>
capitalizzaz<N-ione>
capitaneri<N-a>
capitan<N-o>
capitolett<N-o>
capiton<N-e>
capocannonier<N-e>
capoclan<N-non>
capocomic<N-o>
capodann<N-o>
capogrupp<N-o>
capolavor<N-o>
capolis<N-ta>
capoluog<N-o>
capopattugli<N-a>
caporalat<N-o>
caporedattor<N-e>
caporepart<N-o>
capor<N-ione>
caposald<N-o>
capostipit<N-e>
capostruttur<N-a>
capp<N-a>
cappell<N-a>
cappellacc<N-io>
cappellan<N-o>
cappellett<N-o>
cappell<N-o>
cappellucc<N-io>
cappott<N-o>
capron<N-e>
capuffic<N-io>
caratteracc<N-io>
caratur<N-a>
caravan<N-non>
caravanserragl<N-io>
caravell<N-a>
carboidrat<N-o>
carbonar<N-o>
carceraz<N-ione>
carcer<N-e>
cardin<N-e>
cardiochirur<N-gia>
cardiochirurg<N-o>
cardiolog<N-o>
carezz<N-a>
caricament<N-o>
caricator<N-e>
caricatur<N-a>
caricaturis<N-ta>
caric<N-o>
carillon<N-non>
carmelitan<N-o>
carn<N-e>
carnead<N-e>
carnefic<N-e>
carneficin<N-a>
carnet<N-non>
carnier<N-e>
carnivor<N-o>
carogna<N-ta>
caro<N-ta>
carotagg<N-io>
carovan<N-a>
carovi<N-ta>
carpentier<N-e>
carrier<N-a>
carris<N-ta>
carrozz<N-a>
carrozzin<N-a>
carrozzon<N-e>
carrucol<N-a>
cartell<N-a>
cartellet<N-ta>
cartellin<N-o>
cartell<N-o>
cartier<N-a>
cartilagin<N-e>
cartolibreri<N-a>
cartoncin<N-o>
cartooning<N-non>
cas<N-a>
casal<N-e>
casament<N-o>
casa<N-ta>
cascam<N-e>
cascin<N-a>
cascinal<N-e>
caseific<N-io>
casell<N-o>
casermet<N-ta>
casertan<N-o>
cash-flow<N-non>
casin<N-a>
casolar<N-e>
cass<N-a>
cassafort<N-e>
casset<N-ta>
cassett<N-o>
cassintegrat<N-o>
casson<N-e>
cassonett<N-o>
cas<N-ta>
castagn<N-a>
castagn<N-o>
castiglian<N-o>
castig<N-o>
casti<N-tA>
cast<N-o>
castor<N-o>
castraz<N-ione>
castrism<N-o>
castron<N-e>
casupol<N-a>
cataclis<N-ma>
catacomb<N-a>
catalan<N-o>
catapul<N-ta>
catarat<N-ta>
catast<N-o>
catastrof<N-e>
catecumen<N-o>
catenell<N-a>
caterpillar<N-non>
catin<N-o>
cattolici<N-tA>
cattolic<N-o>
cattur<N-a>
caus<N-a>
causal<N-e>
cautel<N-a>
cav<N-a>
cavallett<N-o>
cavallin<N-o>
cavall<N-o>
cavallon<N-e>
cavatin<N-a>
cavator<N-e>
cavi<N-a>
cavill<N-o>
cavolfior<N-e>
ccd<N-non>
cd<N-non>
cd<N-a>
cecchin<N-o>
cecen<N-o>
cecoslovacc<N-a>
cecoslovacc<N-o>
cediment<N-o>
cedolar<N-e>
cedolin<N-o>
cefale<N-a>
ceffon<N-e>
celerin<N-o>
celib<N-e>
cell<N-a>
cellophan<N-e>
cellul<N-a>
cellulit<N-e>
cembal<N-o>
cementeri<N-a>
cementificaz<N-ione>
cement<N-o>
cener<N-e>
cenn<N-o>
centesim<N-o>
centometris<N-ta>
centralinis<N-ta>
centralizzaz<N-ione>
centrism<N-o>
centr<N-o>
centro-nord<N-non>
centrocampis<N-ta>
centrocamp<N-o>
cer<N-a>
ceramic<N-a>
ceramis<N-ta>
cereal<N-e>
cerimoni<N-a>
cerimonier<N-e>
cernier<N-a>
cer<N-o>
certezz<N-a>
certificat<N-o>
certosin<N-o>
cervell<N-o>
cervellon<N-e>
cesell<N-o>
ces<N-io>
cesoi<N-a>
cessate-il-fuoc<N-o>
cessaz<N-ione>
cess<N-o>
cestin<N-o>
cestis<N-ta>
cesur<N-a>
cetace<N-o>
cet<N-o>
cetriol<N-o>
cfc<N-non>
cgil-funz<N-ione>
chador<N-non>
chalet<N-non>
charter<N-non>
check-up<N-non>
chef<N-non>
chel<N-a>
chemioterapi<N-a>
chemioterapic<N-o>
chiaccher<N-a>
chiacchier<N-a>
chiacchiericc<N-io>
chiacchieron<N-e>
chiama<N-ta>
chiarezz<N-a>
chiarificaz<N-ione>
chiariment<N-o>
chiaror<N-e>
chiat<N-ta>
chiav<N-e>
chicc<N-a>
chicc<N-o>
chierichett<N-o>
chieset<N-ta>
chilometr<N-o>
chilowattor<N-a>
chin<N-a>
chiostr<N-o>
chirur<N-gia>
chirurg<N-o>
chiusur<N-a>
choc<N-non>
ciabattin<N-o>
cicalecc<N-io>
cicatric<N-e>
cicatrizzaz<N-ione>
cicc<N-ione>
ciceron<N-e>
ciclic<N-a>
ciclici<N-tA>
cicl<N-o>
cicloamator<N-e>
ciclostilat<N-o>
cicloturis<N-ta>
ciec<N-a>
ciellin<N-o>
ciel<N-o>
cifrar<N-io>
cigl<N-io>
cilen<N-a>
ciliegin<N-a>
cilieg<N-io>
cineclub<N-non>
cinefil<N-o>
cinematograf<N-o>
cineoperator<N-e>
cineseri<N-a>
cingales<N-e>
cinic<N-o>
cinofil<N-o>
cinquantenn<N-io>
cinquantin<N-o>
cin<N-ta>
ciotol<N-a>
cipigl<N-io>
cipp<N-o>
ciprio<N-ta>
circens<N-e>
circoscriz<N-ione>
circuit<N-o>
cirros<N-i>
cist<N-i>
cit<N-ta>
cittadell<N-a>
cittadin<N-a>
cittadinanz<N-a>
cit<N-tA>
città-stat<N-o>
city<N-non>
ciucc<N-io>
ciuff<N-o>
civet<N-ta>
civetteri<N-a>
civil<N-e>
civilis<N-ta>
civilizzaz<N-ione>
clackson<N-non>
clacson<N-non>
clamor<N-e>
clandestini<N-tA>
clangor<N-e>
clarinett<N-o>
class<N-e>
classici<N-tA>
classifica<N-ta>
clausol<N-a>
claustrofobi<N-a>
clav<N-a>
clericalism<N-o>
cliché<N-non>
climatizzator<N-e>
climax<N-non>
clip<N-non>
clister<N-e>
co-pilo<N-ta>
co-protagonis<N-ta>
coacerv<N-o>
coagulaz<N-ione>
coautor<N-e>
cocain<N-a>
cocainoman<N-e>
coccard<N-a>
cocciutaggin<N-e>
coccodrill<N-o>
codificaz<N-ione>
coediz<N-ione>
coefficient<N-e>
coes<N-ione>
coetane<N-a>
coetane<N-o>
cofanett<N-o>
cofir<N-i>
cogl<N-ione>
coglioneri<N-a>
cognac<N-non>
cognat<N-o>
cognom<N-e>
coinquilin<N-o>
cointeressenz<N-a>
cointestatar<N-io>
colabrod<N-o>
colbacc<N-o>
colesterol<N-o>
colic<N-a>
coll<N-a>
collaborant<N-e>
collaborazionis<N-ta>
collagen<N-e>
collan<N-a>
collant<N-e>
collateralism<N-o>
collaudator<N-e>
coll<N-e>
colleg<N-a>
collegament<N-o>
collettin<N-o>
collettivi<N-tA>
collin<N-a>
collis<N-ione>
coll<N-o>
colloqu<N-io>
colm<N-o>
colomb<N-a>
coloni<N-a>
colonialism<N-o>
colonizzaz<N-ione>
colonn<N-a>
colonnat<N-o>
colon<N-o>
colorat<N-o>
coloratur<N-a>
color<N-e>
coloris<N-ta>
colp<N-o>
coltellacc<N-io>
coltella<N-ta>
coltell<N-o>
coltivaz<N-ione>
coltur<N-a>
columnist<N-non>
comandament<N-o>
comandant<N-e>
comar<N-e>
combattivi<N-tA>
combina<N-ta>
combinaz<N-ione>
combust<N-ione>
come<N-ta>
comic<N-o>
comitiv<N-a>
commediant<N-e>
commediograf<N-o>
comment<N-o>
commercialis<N-ta>
commercializzaz<N-ione>
commerciant<N-e>
commiat<N-o>
commissari<N-a>
commissar<N-io>
commoz<N-ione>
comodi<N-tA>
compagn<N-i>
compagni<N-a>
compagnon<N-e>
compars<N-a>
comparsa<N-ta>
compartecipaz<N-ione>
compass<N-ione>
compatibili<N-tA>
compatt<N-o>
competitivi<N-tA>
competitor<N-non>
competitor<N-e>
competiz<N-ione>
compiant<N-o>
compilation<N-non>
compilator<N-e>
compiment<N-o>
compitin<N-o>
compiutezz<N-a>
complementari<N-tA>
complement<N-o>
complessin<N-o>
completezz<N-a>
complicanz<N-a>
complicaz<N-ione>
complic<N-e>
compliment<N-o>
component<N-e>
comportament<N-o>
compositor<N-e>
comprator<N-e>
comprens<N-ione>
comprensor<N-io>
compresenz<N-a>
compress<N-a>
compressor<N-e>
comput<N-o>
comunicabili<N-tA>
comunicator<N-e>
comunicaz<N-ione>
comun<N-ione>
comunis<N-ta>
comunitar<N-io>
comuni<N-tA>
concatenaz<N-ione>
concentraz<N-ione>
concertat<N-o>
concert<N-o>
concett<N-o>
conchigli<N-a>
conciliaz<N-ione>
concim<N-e>
concistor<N-o>
concitaz<N-ione>
concomitanz<N-a>
concordanz<N-a>
concordi<N-a>
concorrent<N-e>
concorrenz<N-a>
concorrenziali<N-tA>
concors<N-o>
concuss<N-ione>
concussor<N-e>
condanna<N-ta>
condensaz<N-ione>
condic<N-io>
condirettor<N-e>
condiscendenz<N-a>
condivis<N-ione>
condom<N-non>
conduttor<N-e>
conduttur<N-a>
conduz<N-ione>
confederal<N-e>
conferiment<N-o>
confessional<N-e>
confess<N-ione>
confessor<N-e>
confezionament<N-o>
confezionator<N-e>
confez<N-ione>
confinament<N-o>
confindustri<N-a>
confin<N-o>
confisc<N-a>
conflitt<N-o>
conflittuali<N-tA>
confluenz<N-a>
confont<N-o>
conformaz<N-ione>
conformism<N-o>
conformis<N-ta>
conformi<N-tA>
confront<N-o>
congegn<N-o>
congelator<N-e>
conglomerat<N-o>
congoles<N-e>
congreg<N-a>
congregaz<N-ione>
congressis<N-ta>
congrui<N-tA>
conigliet<N-ta>
conigl<N-io>
coniug<N-e>
connotat<N-o>
connotaz<N-ione>
con<N-o>
conoscitor<N-e>
conquistator<N-e>
consacraz<N-ione>
conseguiment<N-o>
consenzient<N-e>
conserv<N-a>
conservator<N-io>
consideraz<N-ione>
consiglier<N-e>
consocia<N-ta>
consociativism<N-o>
consoll<N-e>
consorell<N-a>
consort<N-e>
consuetudin<N-e>
consul<N-ta>
consultaz<N-ione>
consultor<N-io>
consumatric<N-e>
consumaz<N-ione>
consuntiv<N-o>
contabil<N-e>
contachilometr<N-i>
contagocc<N-e>
contaminaz<N-ione>
contator<N-e>
conte<N-a>
contegg<N-io>
contemplaz<N-ione>
contemporanei<N-tA>
contemporane<N-o>
contendent<N-e>
content<N-o>
contenut<N-o>
conterrane<N-o>
contes<N-a>
contestat<N-o>
contestaz<N-ione>
contest<N-o>
contestuali<N-tA>
contingentament<N-o>
contingenz<N-a>
continuism<N-o>
contort<N-o>
contradaiol<N-o>
contraddittor<N-e>
contralt<N-o>
contrammiragl<N-io>
contrappes<N-o>
contrapposiz<N-ione>
contrappunt<N-o>
contrarie<N-tA>
contrassegn<N-o>
contrattemp<N-o>
contraz<N-ione>
contribut<N-o>
contribuz<N-ione>
controcamp<N-o>
controcant<N-o>
controcultur<N-a>
controdeduz<N-ione>
controffensiv<N-a>
contromoss<N-a>
controperizi<N-a>
contropiedis<N-ta>
contropoter<N-e>
contropropos<N-ta>
controreplic<N-a>
controrifor<N-ma>
controscen<N-a>
controsoffitt<N-o>
controspionagg<N-io>
controvalor<N-e>
controvial<N-e>
convent<N-io>
convention<N-non>
convenut<N-o>
convenz<N-ione>
conversar<N-e>
conversaz<N-ione>
convertibili<N-tA>
convertitor<N-e>
convez<N-ione>
convinciment<N-o>
convitat<N-o>
convivent<N-e>
coordina<N-ta>
coordinatric<N-e>
coordinaz<N-ione>
coper<N-ta>
copert<N-o>
coperton<N-e>
copis<N-ta>
coppet<N-ta>
coppi<N-a>
coppiet<N-ta>
copresident<N-e>
copricap<N-o>
coproduz<N-ione>
corall<N-o>
corbelleri<N-a>
cordogl<N-io>
coris<N-ta>
corleones<N-e>
cornacchi<N-a>
cornamus<N-a>
corne<N-a>
corner<N-non>
coroncin<N-a>
corpett<N-o>
corpicin<N-o>
corporatur<N-a>
corposi<N-tA>
correnton<N-e>
corresponsabili<N-tA>
correttezz<N-a>
correttiv<N-o>
corrier<N-a>
corrispondent<N-e>
corrispondenz<N-a>
corros<N-ione>
corsar<N-o>
cors<N-o>
cortigian<N-o>
cortin<N-a>
cortines<N-e>
cort<N-o>
cortocircuit<N-o>
cos<N-a>
cosacc<N-o>
cosc<N-a>
cosceneggiator<N-e>
coset<N-ta>
cosmetic<N-o>
cosmogoni<N-a>
cosmonau<N-ta>
cospirator<N-e>
cossighian<N-o>
costanz<N-a>
costataz<N-ione>
costituzionalism<N-o>
costriz<N-ione>
costrutt<N-o>
costruttor<N-e>
costum<N-e>
costumin<N-o>
cotonific<N-io>
cot<N-ta>
cottur<N-a>
coturn<N-o>
coté<N-non>
coupè<N-non>
coutur<N-e>
cov<N-o>
cow<N-non>
cozz<N-o>
crac<N-non>
cran<N-io>
cravattin<N-o>
creanz<N-a>
creatin<N-a>
creaz<N-ione>
credent<N-e>
credibili<N-tA>
credit<N-o>
creduli<N-tA>
credulon<N-e>
cremaz<N-ione>
cremones<N-e>
crepacc<N-io>
cre<N-ta>
cretes<N-e>
cretin<N-o>
cricc<N-a>
criminalizzaz<N-ione>
crinal<N-e>
crinolin<N-a>
crip<N-ta>
cristallizzaz<N-ione>
cristall<N-o>
crist<N-o>
criter<N-io>
critici<N-tA>
croat<N-o>
croato-bosniac<N-o>
crocch<N-io>
crocefiss<N-o>
crocet<N-ta>
crocevi<N-a>
crocifiss<N-o>
crogiol<N-o>
crogiuol<N-o>
croll<N-o>
cronic<N-o>
cronis<N-ta>
cronistori<N-a>
cron<N-o>
cronolo<N-gia>
cronoscala<N-ta>
crucc<N-o>
crudel<N-tA>
cruis<N-e>
crumir<N-o>
cuban<N-o>
cubatur<N-a>
cubism<N-o>
cubis<N-ta>
cub<N-o>
cuccet<N-ta>
cucchiain<N-o>
cucciol<N-o>
cucin<N-a>
cucinier<N-e>
cucitur<N-a>
cuffi<N-a>
cuginet<N-ta>
culmin<N-e>
culon<N-e>
cult<N-non>
cultur<N-a>
cunees<N-e>
cune<N-o>
cunet<N-ta>
cunicol<N-o>
cuoricin<N-o>
cupezz<N-a>
cupol<N-a>
cupolon<N-e>
curator<N-e>
curatric<N-e>
curi<N-a>
curiosi<N-tA>
curvatur<N-a>
curvon<N-e>
custodi<N-a>
cyberspaz<N-io>
dadaism<N-o>
dagherrotip<N-o>
danar<N-o>
danc<N-e>
dannat<N-o>
dannaz<N-ione>
danneggiament<N-o>
dann<N-o>
danz<N-a>
danzatric<N-e>
databas<N-e>
dataz<N-ione>
datter<N-o>
dattiloscritt<N-o>
daz<N-ione>
ddl<N-non>
deambulaz<N-ione>
debacl<N-e>
debit<N-o>
debitor<N-e>
debutt<N-o>
decadent<N-e>
decadenz<N-a>
decedut<N-o>
decess<N-o>
decis<N-ione>
decisionis<N-ta>
decisor<N-e>
declassament<N-o>
declinaz<N-ione>
declin<N-o>
decoder<N-non>
decodificator<N-e>
decoll<N-o>
decolonizzaz<N-ione>
decontribuz<N-ione>
decoraz<N-ione>
decors<N-o>
decot<N-ta>
decrement<N-o>
decrepi<N-ta>
decretaz<N-ione>
decret<N-o>
dedic<N-a>
deducibili<N-tA>
deejay<N-non>
defaillanc<N-e>
defez<N-ione>
defibrillator<N-e>
defilè<N-non>
defilé<N-non>
definiz<N-ione>
deflaz<N-ione>
deflettor<N-e>
deformi<N-tA>
degent<N-e>
deindustrializzaz<N-ione>
delaz<N-ione>
delegificaz<N-ione>
delegittimaz<N-ione>
delfin<N-o>
delibaz<N-ione>
deliberaz<N-ione>
delimitaz<N-ione>
delinquenz<N-a>
delizi<N-a>
demagog<N-o>
deman<N-io>
demarcaz<N-ione>
demenz<N-a>
demiurg<N-o>
democratic<N-o>
democrazi<N-a>
demografi<N-a>
demolitor<N-e>
demoniac<N-o>
demoniett<N-o>
denatali<N-tA>
denominaz<N-ione>
densi<N-tA>
dentatur<N-a>
dentifric<N-io>
dentin<N-o>
dentis<N-ta>
denun<N-cia>
denunciant<N-e>
deodorant<N-e>
depauperament<N-o>
deperiment<N-o>
deposiz<N-ione>
depost<N-o>
depravaz<N-ione>
depress<N-a>
depress<N-ione>
depress<N-o>
deprezzament<N-o>
dervisc<N-io>
desc<N-o>
desert<N-o>
desistenz<N-a>
despo<N-ta>
destabilizzaz<N-ione>
destalinizzaz<N-ione>
destinaz<N-ione>
destituz<N-ione>
destrezz<N-a>
destr<N-o>
destrutturaz<N-ione>
detentor<N-e>
detenz<N-ione>
detergent<N-e>
deteriorament<N-o>
determinant<N-e>
deterrent<N-e>
deterrenz<N-a>
detonator<N-e>
detraibili<N-tA>
dettagliant<N-e>
dettat<N-o>
deus<N-non>
devo<N-ta>
devot<N-o>
devoz<N-ione>
dg<N-non>
diabetic<N-o>
diafram<N-ma>
diagnos<N-i>
dialett<N-o>
dialis<N-i>
dializzat<N-o>
dialoghett<N-o>
diamant<N-e>
diametr<N-o>
diarre<N-a>
diatrib<N-a>
dibattiment<N-o>
dibattitt<N-o>
dichiarant<N-e>
diciassettenn<N-e>
dicitur<N-a>
didattic<N-a>
diesel<N-non>
dietrofront<N-non>
dietrolo<N-gia>
dietrolog<N-o>
difensivism<N-o>
diffamator<N-e>
diffamaz<N-ione>
difficol<N-tA>
diffidenz<N-a>
difformi<N-tA>
digest<N-ione>
dignitar<N-io>
digress<N-ione>
dilegg<N-io>
dilet<N-ta>
dilettant<N-e>
diluiz<N-ione>
dimess<N-o>
dimissionar<N-io>
dimiss<N-ione>
dinasti<N-a>
d<N-io>
dioces<N-i>
dipint<N-o>
diplo<N-ma>
diplomatic<N-o>
diplomat<N-o>
direttor<N-e>
direz<N-ione>
dirigism<N-o>
dirimpettai<N-a>
dirittt<N-o>
dirottament<N-o>
dirup<N-o>
disabili<N-tA>
disadattat<N-o>
disag<N-io>
disamin<N-a>
disappunt<N-o>
disarmat<N-o>
disarm<N-o>
disarmoni<N-a>
disavanz<N-o>
disavventur<N-a>
disbrig<N-o>
discendenz<N-a>
discepol<N-a>
discerniment<N-o>
discesis<N-ta>
disciplin<N-a>
discobol<N-o>
discol<N-o>
discolp<N-a>
discordanz<N-a>
discordi<N-a>
discotec<N-a>
discount<N-non>
discrepanz<N-a>
discrezionali<N-tA>
discrez<N-ione>
discriminaz<N-ione>
discrimin<N-e>
discuss<N-ione>
disdet<N-ta>
disegnin<N-o>
disegn<N-o>
diserbant<N-e>
diseredat<N-o>
disfunz<N-ione>
disgel<N-o>
disgraziat<N-o>
disgregaz<N-ione>
disgust<N-o>
disillus<N-o>
disimpegn<N-o>
disincant<N-o>
disinfestaz<N-ione>
disinfettant<N-e>
disinformaz<N-ione>
disingann<N-o>
disinteress<N-e>
disinvolt<N-o>
dislocament<N-o>
dislocaz<N-ione>
dismisur<N-a>
disobbedienz<N-a>
disoccupaz<N-ione>
disomogenei<N-tA>
dispacc<N-io>
dispari<N-tA>
dispend<N-io>
dispens<N-a>
dispepsi<N-a>
disperat<N-o>
disperaz<N-ione>
dispiacer<N-e>
dispiegament<N-o>
display<N-non>
disposiz<N-ione>
dispos<N-ta>
dispotism<N-o>
dispu<N-ta>
disquisiz<N-ione>
dissacrator<N-e>
dissalator<N-e>
disseminaz<N-ione>
dissens<N-o>
dissenzient<N-e>
dissequestr<N-o>
dissest<N-o>
dissident<N-e>
dissimulaz<N-ione>
dissipatezz<N-a>
dissipator<N-e>
dissipaz<N-ione>
dissociaz<N-ione>
dissolutezz<N-a>
dissoluz<N-ione>
distacc<N-o>
distens<N-ione>
distes<N-a>
distillat<N-o>
distillator<N-e>
distillaz<N-ione>
distilleri<N-a>
distin<N-ta>
distors<N-ione>
distrat<N-ta>
distruz<N-ione>
disturbator<N-e>
disuguaglianz<N-a>
disuman<N-a>
ditin<N-o>
dittatur<N-a>
divagaz<N-ione>
divan<N-o>
divar<N-io>
diversificaz<N-ione>
divers<N-ione>
diversi<N-tA>
diversiv<N-o>
divertimentific<N-io>
divet<N-ta>
divini<N-tA>
divism<N-o>
div<N-o>
divorator<N-e>
dj<N-non>
dn<N-a>
d<N-o>
docent<N-e>
documentar<N-io>
documentaris<N-ta>
document<N-o>
doganier<N-e>
dog<N-ma>
dogmatism<N-o>
dollar<N-o>
dol<N-o>
dolorett<N-o>
dolorin<N-o>
domand<N-a>
domandin<N-a>
doman<N-i>
domestic<N-o>
don<N-non>
donator<N-e>
donatric<N-e>
donaz<N-ione>
donn<N-a>
donnac<N-cia>
donnaiol<N-o>
don<N-o>
donzell<N-a>
dopamin<N-a>
doping<N-non>
dopo-terremot<N-o>
dopo-vot<N-o>
dopobors<N-a>
dopp<N-io>
doppiogiochis<N-ta>
dopp<N-ione>
dormigl<N-ione>
dormi<N-ta>
doroteism<N-o>
dosagg<N-io>
dossier<N-non>
dottrin<N-a>
dover<N-e>
dragamin<N-e>
drag<N-o>
dram<N-ma>
drapp<N-o>
drenagg<N-io>
driver<N-non>
drogheri<N-a>
dromedar<N-io>
drop<N-non>
ds<N-non>
dt<N-non>
dualism<N-o>
dubb<N-io>
dubbios<N-o>
duc<N-a>
duchess<N-a>
due-giorn<N-i>
dun<N-a>
du<N-o>
duopol<N-io>
duttili<N-tA>
décolleté<N-non>
décor<N-non>
déjà<N-non>
démon<N-e>
dì<N-non>
ebanis<N-ta>
ecatomb<N-e>
eccedenz<N-a>
eccellenz<N-a>
eccentric<N-o>
eccitant<N-e>
ecliss<N-e>
ecliss<N-i>
ecografi<N-a>
economici<N-tA>
ecotass<N-a>
ecoterroris<N-ta>
ectoplas<N-ma>
edicol<N-a>
edificaz<N-ione>
edific<N-io>
edil<N-e>
editorialis<N-ta>
efeb<N-o>
efferat<N-o>
effettacc<N-io>
effig<N-e>
effigi<N-e>
effimer<N-a>
effimer<N-o>
egizian<N-a>
eg<N-o>
elaborat<N-o>
elaboraz<N-ione>
elastic<N-o>
eleganz<N-a>
ele<N-gia>
element<N-o>
elet<N-ta>
elett<N-o>
elettor<N-e>
elettrochoc<N-non>
elettrod<N-o>
elettrodott<N-o>
elettron<N-e>
elettronic<N-a>
elettrotecnic<N-o>
elevaz<N-ione>
eliminatori<N-a>
elisir<N-non>
elit<N-e>
elliss<N-e>
elucubraz<N-ione>
emanaz<N-ione>
ematolog<N-o>
emato<N-ma>
embarg<N-o>
embr<N-ione>
emers<N-ione>
emirat<N-o>
emisfer<N-o>
emofiliac<N-o>
emorra<N-gia>
empor<N-io>
emul<N-o>
emuls<N-ione>
encom<N-io>
ener<N-gia>
enfatizzaz<N-ione>
enotec<N-a>
enti<N-tA>
entomolog<N-o>
entourag<N-e>
enzi<N-ma>
epatit<N-e>
epatopati<N-a>
epidemi<N-a>
epifani<N-a>
epigraf<N-e>
epitaff<N-io>
epitel<N-io>
epitet<N-o>
epope<N-a>
equaz<N-ione>
equilibris<N-ta>
equilibr<N-o>
equipagg<N-io>
equiparaz<N-ione>
equip<N-e>
equi<N-tA>
equivalenz<N-a>
equivoc<N-o>
er<N-a>
erbac<N-cia>
erbet<N-ta>
ered<N-e>
ereditier<N-a>
eredi<N-tA>
eretism<N-o>
ergastolan<N-o>
ermellin<N-o>
ermetic<N-o>
erni<N-a>
ero<N-e>
erogator<N-e>
eroic<N-a>
eroism<N-o>
eros<N-ione>
erudiz<N-ione>
esalaz<N-ione>
esaminator<N-e>
esasperaz<N-ione>
esattori<N-a>
escalation<N-non>
escavatric<N-e>
escavaz<N-ione>
esclamaz<N-ione>
esclus<N-o>
escrescenz<N-a>
escurs<N-ione>
eseges<N-i>
esequi<N-a>
esercitaz<N-ione>
eserciz<N-io>
esibiz<N-ione>
esibizionism<N-o>
esigent<N-e>
esigenz<N-a>
esil<N-io>
esistenzialis<N-ta>
esit<N-o>
esod<N-o>
esoner<N-o>
esorcism<N-o>
esorcis<N-ta>
esordient<N-e>
esord<N-io>
espans<N-ione>
espedient<N-e>
esperienz<N-a>
espiant<N-o>
esplos<N-ione>
esplosiv<N-o>
espositor<N-e>
esposiz<N-ione>
esposto-denun<N-cia>
espressionism<N-o>
espressivi<N-tA>
espropr<N-io>
espuls<N-ione>
esquimes<N-e>
esserin<N-o>
establishment<N-non>
estat<N-e>
estens<N-ione>
estensor<N-e>
esternaz<N-ione>
estetic<N-a>
estetism<N-o>
estetis<N-ta>
estimator<N-e>
estinz<N-ione>
eston<N-e>
estrane<N-a>
estranei<N-tA>
estrane<N-o>
estratt<N-o>
estraz<N-ione>
estremi<N-tA>
estrinsecaz<N-ione>
estromiss<N-ione>
estrosi<N-tA>
esuberanz<N-a>
eterni<N-tA>
etern<N-o>
eteronim<N-o>
etichet<N-ta>
etichettatur<N-a>
etiop<N-e>
etnì<N-a>
etolog<N-o>
etrusc<N-o>
ettar<N-o>
ett<N-o>
eufemism<N-o>
eufori<N-a>
eurobbligaz<N-ione>
europeism<N-o>
europeis<N-ta>
eutanasi<N-a>
evangelic<N-o>
evangelis<N-ta>
evas<N-ione>
evidenz<N-a>
evocaz<N-ione>
evoluz<N-ione>
ex-alleat<N-o>
ex-comunis<N-ta>
ex-consiglier<N-e>
ex-dipendent<N-e>
ex-ministr<N-o>
exploit<N-non>
fabbric<N-a>
fabbricat<N-o>
fabbricator<N-e>
fabbricaz<N-ione>
fabulaz<N-ione>
faccend<N-a>
faccendier<N-e>
faccet<N-ta>
facilitaz<N-ione>
facili<N-tA>
facilon<N-e>
facitor<N-e>
facoltativi<N-tA>
facol<N-tA>
factoring<N-non>
factotum<N-non>
fagg<N-io>
fagottin<N-o>
fagott<N-o>
faid<N-a>
falangis<N-ta>
falca<N-ta>
falcon<N-e>
falegnam<N-e>
falen<N-a>
fall<N-a>
fall<N-o>
falsi<N-tA>
fals<N-o>
famelic<N-o>
famigliol<N-a>
familiar<N-e>
fan<N-non>
fanal<N-e>
fanciullezz<N-a>
fanfanian<N-o>
fans<N-non>
fantasi<N-a>
fantasis<N-ta>
fantas<N-ma>
fantin<N-o>
faraon<N-e>
farett<N-o>
farma<N-cia>
farmac<N-o>
farmer<N-non>
farneticaz<N-ione>
farraginosi<N-tA>
fars<N-a>
fascet<N-ta>
fasciatur<N-a>
fascicolett<N-o>
fascicol<N-o>
fascin<N-o>
fasc<N-io>
fascism<N-o>
fastid<N-io>
fast<N-o>
fatali<N-tA>
faticator<N-e>
fattibili<N-tA>
fattorin<N-o>
fattur<N-a>
fatturat<N-o>
fatui<N-tA>
faun<N-a>
faun<N-o>
favol<N-a>
favoreggiament<N-o>
favoreggiator<N-e>
favoritism<N-o>
favorit<N-o>
faz<N-ione>
faziosi<N-tA>
fazios<N-o>
fazzolettin<N-o>
fec<N-cia>
fed<N-e>
fedelissim<N-o>
federcalc<N-io>
feeling<N-non>
fegat<N-o>
felp<N-a>
feluc<N-a>
femminili<N-tA>
femminuc<N-cia>
fenditur<N-a>
fenic<N-e>
fenic<N-io>
fenicotter<N-o>
fenomen<N-o>
ferma<N-ta>
fermat<N-o>
ferment<N-o>
ferraris<N-ta>
ferr<N-o>
fertilizzant<N-e>
fervor<N-e>
fessur<N-a>
feston<N-e>
feticc<N-io>
fet<N-ta>
feudalesim<N-o>
feudatar<N-io>
fez<N-non>
fiab<N-a>
fiacc<N-o>
fial<N-a>
fiamma<N-ta>
fiammell<N-a>
fiammifer<N-o>
fiancheggiator<N-e>
fibro<N-ma>
fibros<N-i>
fic<N-o>
ficus<N-non>
fidanzatin<N-a>
fidejuss<N-ione>
fidu<N-cia>
fiduciant<N-e>
fiduciari<N-a>
fiduciar<N-io>
fien<N-o>
fier<N-a>
figliastr<N-o>
figl<N-io>
figliocc<N-io>
figliol<N-o>
figliuol<N-o>
figur<N-a>
figuraz<N-ione>
figuret<N-ta>
figurin<N-o>
filament<N-o>
filarmonic<N-a>
filatelic<N-o>
filatric<N-e>
fil<N-e>
filin<N-o>
filippic<N-a>
filippin<N-a>
filiste<N-o>
film-tv<N-non>
film-veri<N-tA>
filmaker<N-non>
filmin<N-o>
final<N-e>
finali<N-tA>
finalizzaz<N-ione>
finanziari<N-a>
finanziator<N-e>
finaziament<N-o>
finestr<N-a>
finestrell<N-a>
finestrin<N-o>
finestron<N-e>
finlandes<N-e>
finmeccanic<N-a>
finocch<N-io>
finz<N-ione>
fiocchett<N-o>
fiora<N-io>
fiord<N-o>
fior<N-e>
fiorentin<N-a>
fiorentin<N-o>
fiorettis<N-ta>
fioritur<N-a>
fiott<N-o>
firmatar<N-io>
fisarmonic<N-a>
fiscal<N-e>
fiscali<N-tA>
fischiett<N-o>
fisc<N-o>
fisici<N-tA>
fisic<N-o>
fisiognomic<N-a>
fisiolog<N-o>
fisioterapis<N-ta>
fiss<N-ione>
fistol<N-a>
fit<N-ta>
fium<N-e>
fixing<N-non>
flacon<N-e>
flagell<N-o>
flamenc<N-o>
flanell<N-a>
flash<N-non>
flashback<N-non>
flatulenz<N-a>
flautis<N-ta>
flem<N-ma>
flot<N-ta>
fluid<N-o>
fluor<N-o>
fluss<N-o>
flutt<N-o>
fluttuaz<N-ione>
foc<N-a>
focolar<N-e>
fog<N-a>
fog<N-gia>
foggian<N-o>
fogliettin<N-o>
fogliolin<N-a>
fognatur<N-a>
foib<N-a>
fol<N-a>
fola<N-ta>
foll<N-a>
follicol<N-o>
fomentator<N-e>
fondamentalis<N-ta>
fondator<N-e>
fondell<N-o>
fondis<N-ta>
fond<N-o>
fondovall<N-e>
fonic<N-o>
fonogram<N-ma>
fontanell<N-a>
football<N-non>
foragg<N-io>
forcaiol<N-o>
forcell<N-a>
forchet<N-ta>
forcon<N-e>
forellin<N-o>
foresteri<N-a>
forestier<N-o>
for<N-ma>
forma-partit<N-o>
formagg<N-io>
formalis<N-ta>
formali<N-tA>
formalizzaz<N-ione>
format<N-non>
formell<N-a>
formic<N-a>
formica<N-io>
formulet<N-ta>
forna<N-io>
fornell<N-o>
fornicaz<N-ione>
forsennat<N-o>
fort<N-e>
fortezz<N-a>
fortificaz<N-ione>
fortunal<N-e>
forza-lavor<N-o>
forzut<N-o>
fossat<N-o>
fosset<N-ta>
fossil<N-e>
fotocolor<N-non>
fotograf<N-a>
fotografi<N-a>
fotomodell<N-a>
fragili<N-tA>
fragol<N-a>
fragranz<N-a>
fraintendiment<N-o>
framment<N-o>
fran<N-a>
francescan<N-a>
franchism<N-o>
franchisor<N-non>
franc<N-o>
francofon<N-o>
frangent<N-e>
frantumaz<N-ione>
frasar<N-io>
fras<N-e>
frasegg<N-io>
fraseolo<N-gia>
fratellanz<N-a>
fraterni<N-tA>
frattemp<N-o>
frattur<N-a>
frazionament<N-o>
freccet<N-ta>
frec<N-cia>
fredd<N-o>
freg<N-io>
fregol<N-a>
fremit<N-o>
frenetic<N-a>
frequentaz<N-ione>
fret<N-ta>
freudian<N-o>
frittell<N-a>
frittur<N-a>
frivolezz<N-a>
frivol<N-o>
froc<N-io>
frond<N-a>
front<N-e>
frontespiz<N-io>
frontier<N-a>
fronton<N-e>
fruiz<N-ione>
frullator<N-e>
frusc<N-io>
frus<N-ta>
frustrat<N-o>
frustraz<N-ione>
fucilaz<N-ione>
fuggi-fugg<N-i>
fuggitiv<N-o>
fulcr<N-o>
fulminant<N-e>
fuma<N-ta>
fumett<N-o>
fumetton<N-e>
fumisteri<N-a>
fum<N-o>
funambol<N-o>
funest<N-o>
fung<N-o>
funky<N-non>
funzionali<N-tA>
funzionar<N-io>
funz<N-ione>
fuoribord<N-o>
fuoriusci<N-ta>
fuoruscit<N-o>
furbacch<N-ione>
furba<N-ta>
furberi<N-a>
fureri<N-a>
furfant<N-e>
furgon<N-e>
furlan<N-o>
fus<N-ione>
fus<N-o>
fustin<N-o>
fust<N-o>
futures<N-non>
futur<N-o>
futurolog<N-o>
gabbianell<N-a>
gabbiet<N-ta>
gabb<N-ione>
gabbiott<N-o>
gabellier<N-e>
gaff<N-e>
gag<N-non>
gagà<N-non>
galantuom<N-o>
galassi<N-a>
galleggiament<N-o>
galleris<N-ta>
gallett<N-o>
gallon<N-e>
galoppin<N-o>
galà<N-non>
gamb<N-a>
gambet<N-ta>
gambon<N-a>
gam<N-e>
gam<N-ma>
gap<N-non>
garba<N-ta>
garb<N-o>
gardeni<N-a>
garzon<N-e>
gas<N-non>
gasdott<N-o>
gastrit<N-e>
gat<N-ta>
gaviane<N-o>
gay<N-non>
gazz<N-a>
gelateri<N-a>
gelatin<N-a>
geles<N-e>
gelsomin<N-o>
gemellagg<N-io>
gemell<N-o>
gemit<N-o>
gendarm<N-e>
gen<N-e>
generali<N-tA>
generalon<N-e>
generaz<N-ione>
generosi<N-tA>
genes<N-i>
genetic<N-a>
genetis<N-ta>
gengiv<N-a>
geni<N-a>
geniacc<N-io>
genier<N-e>
genoan<N-o>
gentleman<N-non>
genuin<N-o>
genì<N-a>
geografi<N-a>
geograf<N-o>
geometri<N-a>
gerarc<N-a>
geremiad<N-e>
germogl<N-io>
gerontolog<N-o>
gessat<N-o>
gessett<N-o>
gestant<N-e>
gesticolaz<N-ione>
gettit<N-o>
gett<N-o>
getton<N-e>
ghepard<N-o>
gherminell<N-a>
ghiaccia<N-io>
ghiai<N-a>
ghigliottin<N-a>
ghign<N-o>
ghiribizz<N-o>
ghirigor<N-o>
ghirland<N-a>
giacchet<N-ta>
giaccon<N-e>
giacenz<N-a>
giaciment<N-o>
giacobin<N-o>
giall<N-o>
gianduiott<N-o>
giapponesin<N-o>
giardinier<N-e>
giarrettier<N-a>
giavellott<N-o>
gigantism<N-o>
gigantografi<N-a>
giganton<N-e>
gigl<N-io>
gilè<N-non>
gimkan<N-a>
gin<N-non>
ginecolog<N-a>
ginecolog<N-o>
ginevrin<N-o>
gingill<N-o>
ginnasial<N-e>
ginnas<N-ta>
giocator<N-e>
giocatric<N-e>
giocattola<N-io>
giog<N-o>
gioiell<N-o>
giornalacc<N-io>
giornalett<N-o>
giornalism<N-o>
giornalis<N-ta>
giorna<N-ta>
giostra<N-io>
giovan<N-e>
giovanet<N-ta>
giovanott<N-o>
giovanotton<N-e>
giovedì<N-non>
giovinastr<N-o>
giovinet<N-ta>
giovinett<N-o>
giovinott<N-o>
gip<N-non>
giramond<N-o>
giravol<N-ta>
gir<N-o>
giron<N-e>
girotond<N-o>
gi<N-ta>
gitta<N-ta>
giubbin<N-o>
giubil<N-o>
giudicant<N-e>
giudic<N-e>
giudiz<N-io>
giuntur<N-a>
giuoc<N-o>
giurament<N-o>
giustificaz<N-ione>
giustificazionism<N-o>
giustizi<N-a>
giustizialism<N-o>
gladiator<N-e>
glasnost<N-non>
gleb<N-a>
glob<N-o>
glori<N-a>
gloss<N-a>
glucos<N-io>
glute<N-o>
gnocc<N-o>
gnom<N-o>
gobb<N-a>
gobb<N-o>
goduri<N-a>
gol-fantas<N-ma>
golead<N-a>
golf<N-non>
golfett<N-o>
golfin<N-o>
golfis<N-ta>
golf<N-o>
golfon<N-e>
goliarda<N-ta>
goliardi<N-a>
goliard<N-o>
gollett<N-o>
golosi<N-tA>
gomit<N-o>
gommon<N-e>
gondol<N-a>
gonfi<N-a>
gonn<N-a>
gonnell<N-a>
gonz<N-o>
gospel<N-non>
go<N-ta>
governabili<N-tA>
governatorat<N-o>
governator<N-e>
gozz<N-o>
gozzovigli<N-a>
gradevolezz<N-a>
gradiment<N-o>
gradina<N-ta>
graduali<N-tA>
graduat<N-o>
graduatori<N-a>
graffet<N-ta>
graffit<N-o>
grana<N-io>
grancass<N-a>
grandin<N-e>
grappin<N-o>
grappol<N-o>
grass<N-o>
grattacap<N-o>
grattaciel<N-o>
gravidanz<N-a>
gravitaz<N-ione>
gravi<N-tA>
grecis<N-ta>
greci<N-tA>
grec<N-o>
grembiulin<N-o>
grembiulon<N-e>
greppi<N-a>
gret<N-o>
gridolin<N-o>
grifon<N-e>
grig<N-io>
griglia<N-ta>
grill<N-non>
grill<N-o>
grimaldell<N-o>
grisagli<N-a>
grondai<N-a>
gropp<N-o>
grossis<N-ta>
grossolan<N-a>
grot<N-ta>
grottesc<N-o>
grum<N-o>
grupp<N-o>
gruppuscol<N-o>
guadagn<N-o>
guain<N-a>
guant<N-o>
guard-rail<N-non>
guardarob<N-a>
guardiacac<N-cia>
guardiaspall<N-e>
guardrail<N-non>
guarig<N-ione>
guarnig<N-ione>
guascona<N-ta>
guatemaltec<N-o>
guerr<N-a>
guerrier<N-a>
guerrier<N-o>
guerrigli<N-a>
gugli<N-a>
guid<N-a>
guidabili<N-tA>
guidator<N-e>
guinzagl<N-io>
guizz<N-o>
gup<N-non>
gusc<N-io>
haitian<N-o>
han<N-non>
hangar<N-non>
harem<N-non>
hit<N-non>
hobby<N-non>
holding<N-non>
hooligan<N-non>
hotel<N-non>
hub<N-non>
iattur<N-a>
ibrid<N-o>
ictus<N-non>
idealis<N-ta>
identificaz<N-ione>
identi<N-tA>
ideogram<N-ma>
ideolog<N-o>
idol<N-o>
idrant<N-e>
idrovor<N-a>
iettator<N-e>
iglo<N-o>
ignoranz<N-a>
ilari<N-tA>
illuminaz<N-ione>
illuminism<N-o>
illus<N-ione>
illustrator<N-e>
imballagg<N-io>
imbarazzat<N-o>
imbarazz<N-o>
imbarbariment<N-o>
imbecill<N-e>
imbecilli<N-tA>
imberb<N-e>
imbottitur<N-a>
imbut<N-o>
immaginaz<N-ione>
immagin<N-e>
immaginific<N-o>
immigrant<N-e>
immigra<N-ta>
immigraz<N-ione>
immobil<N-e>
immobilism<N-o>
immorali<N-tA>
immortali<N-tA>
immunolog<N-o>
impacc<N-io>
impaginaz<N-ione>
impazienz<N-a>
impegn<N-o>
impenitent<N-e>
impenna<N-ta>
imperator<N-e>
imperatric<N-e>
imperfett<N-o>
imper<N-o>
impertinenz<N-a>
impet<N-o>
impiccag<N-ione>
impiegat<N-o>
implicit<N-o>
imploraz<N-ione>
impopolari<N-tA>
importanz<N-a>
importator<N-e>
imposiz<N-ione>
impossibili<N-tA>
impostaz<N-ione>
impostur<N-a>
impoveriment<N-o>
imprenditori<N-a>
impres<N-a>
imprevedibili<N-tA>
imprevist<N-o>
impron<N-ta>
improprie<N-tA>
imprudent<N-e>
impudenz<N-a>
impugnaz<N-ione>
impuni<N-tA>
imputa<N-ta>
inabili<N-tA>
inadempienz<N-a>
inalaz<N-ione>
inaudit<N-o>
incantator<N-e>
incarceraz<N-ione>
incarnat<N-o>
incarnaz<N-ione>
incendiar<N-io>
incend<N-io>
inceneritor<N-e>
incens<N-o>
incensurat<N-o>
incentiv<N-o>
incer<N-ta>
incertezz<N-a>
incert<N-o>
incest<N-o>
incident<N-e>
incis<N-ione>
incisivi<N-tA>
incisor<N-e>
incitament<N-o>
incivil<N-tA>
incogni<N-ta>
incolonnament<N-o>
incolpaz<N-ione>
incolumi<N-tA>
incombenz<N-a>
incompetent<N-e>
incompiut<N-o>
incongruenz<N-a>
incongrui<N-tA>
inconsapevolezz<N-a>
inconsc<N-io>
incontinenz<N-a>
incoronaz<N-ione>
incorporaz<N-ione>
incostanz<N-a>
incostituzionali<N-tA>
incrociator<N-e>
incubator<N-e>
incubatric<N-e>
incuri<N-a>
indagat<N-o>
indebitament<N-o>
indeboliment<N-o>
indecis<N-ione>
indeterminatezz<N-a>
indi<N-a>
indicator<N-e>
indicaz<N-ione>
indigen<N-a>
indigent<N-e>
indignat<N-o>
indipendentism<N-o>
indipendentis<N-ta>
indisciplin<N-a>
indisposiz<N-ione>
individualis<N-ta>
individu<N-o>
indol<N-e>
indomit<N-o>
indonesian<N-o>
indossator<N-e>
indug<N-io>
induriment<N-o>
industri<N-a>
industrialott<N-o>
inefficienz<N-a>
inerzi<N-a>
inesistenz<N-a>
inesperienz<N-a>
inestetism<N-o>
inezi<N-a>
infam<N-e>
infant<N-e>
infantilism<N-o>
infanzi<N-a>
infastidit<N-o>
infaus<N-ta>
infelici<N-tA>
inferenz<N-a>
infermier<N-a>
infermier<N-e>
infermi<N-tA>
inferm<N-o>
infiammaz<N-ione>
infiltraz<N-ione>
infingiment<N-o>
infiss<N-o>
inflessibili<N-tA>
infless<N-ione>
influenz<N-a>
influss<N-o>
informatic<N-a>
informatizzaz<N-ione>
informaz<N-ione>
infortun<N-io>
infrastruttur<N-a>
ingann<N-o>
ingarbuglia<N-ta>
ingegner<N-e>
ingenui<N-tA>
ingerenz<N-a>
ingordi<N-gia>
ingord<N-o>
ingovernabili<N-tA>
ingranagg<N-io>
ingrandiment<N-o>
iniez<N-ione>
inimicizi<N-a>
iniqui<N-tA>
iniziator<N-e>
iniziaz<N-ione>
iniz<N-io>
innalzament<N-o>
innamorat<N-o>
inopportuni<N-tA>
inquadratur<N-a>
inquiet<N-o>
inquirent<N-e>
inquisiz<N-ione>
insabbiator<N-e>
insegnament<N-o>
inseguiment<N-o>
inseguitric<N-e>
inseriment<N-o>
insiem<N-e>
insipienz<N-a>
insistenz<N-a>
insoddisfaz<N-ione>
insolvenz<N-a>
insonn<N-e>
insorgenz<N-a>
insort<N-o>
instabili<N-tA>
installator<N-e>
installaz<N-ione>
insufficienz<N-a>
insurrez<N-ione>
intagliator<N-e>
intasament<N-o>
integrism<N-o>
intelaiatur<N-a>
intellett<N-o>
intellettual<N-e>
intelligenc<N-e>
intelligenz<N-a>
intellighenzi<N-a>
intenditor<N-e>
intensificaz<N-ione>
intercettaz<N-ione>
interconness<N-ione>
interess<N-e>
interlud<N-io>
intermediar<N-io>
intermediaz<N-ione>
internament<N-o>
interport<N-o>
interpret<N-e>
interrogator<N-io>
interruz<N-ione>
interscamb<N-io>
interstiz<N-io>
intervis<N-ta>
intervistat<N-o>
intervistator<N-e>
intervistatric<N-e>
intestaz<N-ione>
intevent<N-o>
intez<N-ione>
intifad<N-a>
intim<N-o>
intrallazz<N-o>
intransigenz<N-a>
intraprendent<N-e>
intraprendenz<N-a>
intratteniment<N-o>
intrattenitor<N-e>
intrecc<N-io>
introduz<N-ione>
intrugl<N-io>
intrus<N-o>
intuiz<N-ione>
invadenz<N-a>
invalidi<N-tA>
invalid<N-o>
invas<N-o>
invecchiament<N-o>
inventar<N-io>
inventor<N-e>
inverosimiglianz<N-a>
invers<N-ione>
investigaz<N-ione>
investitur<N-a>
invettiv<N-a>
invidi<N-a>
invisibili<N-tA>
invitat<N-o>
invocaz<N-ione>
involuz<N-ione>
iod<N-io>
ipersensibili<N-tA>
ipertrofi<N-a>
ippodrom<N-o>
ippopotam<N-o>
irachen<N-o>
iraken<N-o>
irpin<N-o>
irradiaz<N-ione>
irrazionalism<N-o>
irreal<N-tA>
irregolari<N-tA>
irrigaz<N-ione>
irris<N-ione>
irritaz<N-ione>
irriverenz<N-a>
irruenz<N-a>
irruz<N-ione>
iscriz<N-ione>
isol<N-a>
isolament<N-o>
isolan<N-o>
isolat<N-o>
isolazionis<N-ta>
isolet<N-ta>
isolott<N-o>
isotop<N-o>
ispettor<N-e>
ispiraz<N-ione>
istant<N-e>
istigator<N-e>
istigaz<N-ione>
istitutric<N-e>
istrian<N-o>
istr<N-ione>
istruttori<N-a>
istruz<N-ione>
italiani<N-tA>
italian<N-o>
italic<N-o>
italo-american<N-o>
jab<N-non>
jackpot<N-non>
jam<N-non>
jazzis<N-ta>
jeans<N-non>
jet<N-non>
juke-box<N-non>
jungl<N-a>
juventin<N-a>
juventin<N-o>
kalashnikov<N-non>
kefiah<N-non>
kenyan<N-o>
keynesian<N-o>
khmer<N-non>
kibbutz<N-non>
kit<N-non>
kiw<N-i>
koiné<N-non>
kosovar<N-o>
labirint<N-o>
lacc<N-a>
lacc<N-io>
laceraz<N-ione>
lacri<N-ma>
lacrimogen<N-o>
lacrimuc<N-cia>
ladin<N-o>
lagnanz<N-a>
lag<N-o>
lagun<N-a>
laicat<N-o>
laicism<N-o>
laic<N-o>
laissez-fair<N-e>
lambad<N-a>
lamentaz<N-ione>
lamentel<N-a>
lament<N-o>
lamet<N-ta>
laminat<N-o>
lampadin<N-a>
lampeggiant<N-e>
lampeggiator<N-e>
lamp<N-ione>
lamp<N-o>
lampon<N-e>
lan<N-a>
lancet<N-ta>
lanciagranat<N-e>
lanciator<N-e>
lanc<N-io>
lanific<N-io>
larghezz<N-a>
larg<N-o>
larv<N-a>
lastr<N-a>
lastric<N-o>
lateral<N-e>
latifond<N-o>
latinis<N-ta>
latini<N-tA>
latitanz<N-a>
lat<N-o>
latrat<N-o>
latt<N-e>
latteri<N-a>
laure<N-a>
laureand<N-o>
laurea<N-ta>
lavabiancheri<N-a>
lavagg<N-io>
lavand<N-a>
lavativ<N-o>
lavato<N-io>
lavatric<N-e>
lavoracc<N-io>
lavor<N-io>
lazial<N-e>
lazz<N-o>
leader<N-non>
leal<N-tA>
lebbrosar<N-io>
lecces<N-e>
lecches<N-e>
leccorni<N-a>
legal<N-e>
legali<N-tA>
legatur<N-a>
legg<N-e>
legge-quadr<N-o>
leggend<N-a>
leggendari<N-a>
leggerezz<N-a>
leggiadr<N-a>
leggin<N-a>
leghism<N-o>
leghis<N-ta>
legionar<N-io>
leg<N-ione>
legislator<N-e>
legnam<N-e>
lemb<N-o>
len<N-a>
leninism<N-o>
leninis<N-ta>
lenticchi<N-a>
lent<N-o>
lenz<N-a>
leoness<N-a>
lepidezz<N-a>
lesbic<N-a>
lessic<N-o>
lessicograf<N-o>
letterat<N-o>
letteratur<N-a>
lettig<N-a>
lettin<N-o>
lett<N-o>
lettric<N-e>
lev<N-a>
levi<N-tA>
lezioncin<N-a>
lez<N-ione>
libag<N-ione>
libecc<N-io>
liberal<N-non>
liberal-conservator<N-e>
liberaldemocratic<N-o>
liberaldemocrazi<N-a>
liberali<N-tA>
liberian<N-o>
liberism<N-o>
libertin<N-o>
libert<N-o>
libra<N-io>
librett<N-o>
libriccin<N-o>
libr<N-o>
libro-intervis<N-ta>
licei<N-tA>
lice<N-o>
lichen<N-e>
licitaz<N-ione>
lid<N-o>
ligur<N-e>
lillipuzian<N-o>
limb<N-o>
limitaz<N-ione>
limitrof<N-o>
limpidezz<N-a>
linciagg<N-io>
line<N-a>
linf<N-a>
linfonod<N-o>
lingu<N-a>
linguac<N-cia>
linguagg<N-io>
linguet<N-ta>
liquefaz<N-ione>
liquidator<N-e>
liret<N-ta>
liric<N-a>
liric<N-o>
lisc<N-a>
lisc<N-io>
litani<N-a>
lit<N-e>
litigiosi<N-tA>
litografi<N-a>
litoral<N-e>
litr<N-o>
litur<N-gia>
liut<N-o>
livellament<N-o>
livor<N-e>
livornes<N-e>
local<N-e>
locali<N-tA>
locandin<N-a>
location<N-non>
locomotric<N-e>
locuz<N-ione>
lod<N-o>
logg<N-ione>
loggionis<N-ta>
logic<N-a>
logistic<N-a>
log<N-o>
lomb<N-o>
lombric<N-o>
longitudin<N-e>
lontr<N-a>
losc<N-o>
lottizzat<N-o>
lottizzaz<N-ione>
lp<N-non>
luccicant<N-e>
lucernar<N-io>
lucertol<N-a>
lucet<N-ta>
lucr<N-o>
lugl<N-io>
lumac<N-a>
luminari<N-a>
luminescenz<N-a>
lumin<N-o>
lunedì<N-non>
lunet<N-ta>
lungaggin<N-e>
lungagnon<N-e>
lungolag<N-o>
lungometragg<N-io>
lup<N-a>
lupanar<N-e>
lupar<N-a>
lupett<N-o>
luss<N-o>
lustrascarp<N-e>
lustrin<N-o>
lustr<N-o>
luteran<N-o>
macabr<N-o>
maccheron<N-e>
macchi<N-a>
macchinar<N-io>
macchinin<N-a>
macedoni<N-a>
machiavellism<N-o>
mach<N-o>
macroeconomi<N-a>
macromolecol<N-a>
macrostruttur<N-a>
macumb<N-a>
mada<N-ma>
madonn<N-a>
madr<N-e>
madridis<N-ta>
madrigal<N-e>
madrilen<N-o>
maestral<N-e>
maestranz<N-a>
maestr<N-o>
maes<N-tA>
mafi<N-a>
mafiolog<N-o>
mafios<N-o>
magazzinier<N-e>
maggiolin<N-o>
maggioranz<N-a>
maggiordom<N-o>
maggiorenn<N-e>
maghrebin<N-o>
magiar<N-o>
magistrat<N-o>
magliar<N-o>
maglieri<N-a>
maglioncin<N-o>
magnac<N-cia>
magnat<N-e>
magnetism<N-o>
magnificenz<N-a>
magon<N-e>
magì<N-a>
maial<N-e>
maialin<N-o>
maiolic<N-a>
maiones<N-e>
mais<N-non>
make-up<N-non>
mal<N-non>
malaffar<N-e>
malandat<N-o>
malann<N-o>
malari<N-a>
malasort<N-e>
malat<N-o>
malatti<N-a>
malconc<N-io>
maldestr<N-o>
maldicenz<N-a>
mal<N-e>
maledet<N-ta>
maledett<N-o>
maleducaz<N-ione>
malefic<N-io>
malefic<N-o>
males<N-e>
malfattor<N-e>
malgovern<N-o>
maligni<N-tA>
malign<N-o>
malintenzionat<N-o>
malintes<N-o>
mallopp<N-o>
mal<N-ta>
maltemp<N-o>
maltolt<N-o>
maltrattament<N-o>
malumor<N-e>
malvag<N-io>
malvivent<N-e>
mamb<N-o>
mamman<N-a>
mammell<N-a>
mammin<N-a>
mammut<N-non>
man<N-non>
mancament<N-o>
manchevolezz<N-a>
mandant<N-e>
mandatar<N-io>
mandat<N-o>
mandibol<N-a>
mandri<N-a>
manegg<N-ione>
manet<N-ta>
manganella<N-ta>
manganell<N-o>
mangiapret<N-i>
mangiatoi<N-a>
mangimific<N-io>
maniac<N-o>
manicheism<N-o>
manichin<N-o>
manicott<N-o>
manifestant<N-e>
manifestin<N-o>
manifest<N-o>
manigli<N-a>
manipolator<N-e>
manipol<N-o>
man<N-o>
manodoper<N-a>
manomiss<N-ione>
manomor<N-ta>
manoscritt<N-o>
manovrator<N-e>
manovrin<N-a>
mansard<N-a>
mans<N-ione>
mantell<N-a>
mantellin<N-a>
mantell<N-o>
mant<N-o>
manuali<N-tA>
manufatt<N-o>
manì<N-a>
mapp<N-a>
mappamond<N-o>
mar<N-non>
marachell<N-a>
maras<N-ma>
maraton<N-a>
marc<N-a>
marcanton<N-io>
marcator<N-e>
march<N-io>
mar<N-cia>
marciatric<N-e>
marc<N-io>
mare<N-a>
mareggia<N-ta>
maremot<N-o>
maresciall<N-o>
marginal<N-e>
marginalizzaz<N-ione>
marinar<N-a>
marinarett<N-o>
marittim<N-o>
mariuol<N-o>
market<N-non>
marmitton<N-e>
marm<N-o>
marmot<N-ta>
marocchin<N-a>
marsup<N-io>
martella<N-ta>
martell<N-o>
martoria<N-ta>
marxismo-leninism<N-o>
marzian<N-o>
mascalzona<N-ta>
mascalzon<N-e>
mascell<N-a>
mascheratur<N-a>
mascherin<N-a>
mascheron<N-e>
maschilism<N-o>
masch<N-ione>
mascolini<N-tA>
mascott<N-e>
masnad<N-a>
mas<N-o>
masochis<N-ta>
mass<N-a>
massacrator<N-e>
massaggiatric<N-e>
massai<N-a>
massicc<N-io>
massimalis<N-ta>
massim<N-o>
masson<N-e>
mastic<N-e>
matass<N-a>
match<N-non>
match-point<N-non>
matematic<N-a>
material<N-e>
materialism<N-o>
materialis<N-ta>
matrign<N-a>
matriosk<N-a>
matron<N-a>
mattacch<N-ione>
mattan<N-a>
mattanz<N-a>
mattator<N-e>
mattinal<N-e>
mattoncin<N-o>
matton<N-e>
maturand<N-o>
maturaz<N-ione>
maxi-inchies<N-ta>
maxi-operaz<N-ione>
maxi-ter<N-non>
maxiaument<N-o>
maxiconcors<N-o>
maximul<N-ta>
maxiprestit<N-o>
maxiprocess<N-o>
mazzier<N-e>
meccanism<N-o>
meccanizzaz<N-ione>
mecenat<N-e>
medaglier<N-e>
medagliet<N-ta>
medi<N-a>
mediator<N-e>
medicament<N-o>
medicinal<N-e>
medievis<N-ta>
medin<N-a>
mediocredit<N-o>
mediocri<N-tA>
medioeval<N-e>
mediometragg<N-io>
medium<N-non>
medus<N-a>
meeting<N-non>
mega-concert<N-o>
mega-fus<N-ione>
mega-impiant<N-o>
megadirigent<N-e>
megaimpiant<N-o>
megalopol<N-i>
megastruttur<N-a>
melass<N-a>
mel<N-o>
melodi<N-a>
melogran<N-o>
melon<N-e>
melting<N-non>
mement<N-o>
memorandum<N-non>
menag<N-e>
mendicant<N-e>
meningit<N-e>
menisc<N-o>
menomaz<N-ione>
menopaus<N-a>
ment<N-e>
mentecatt<N-o>
mentitor<N-e>
mentor<N-e>
meravigli<N-a>
mercanzi<N-a>
mercenar<N-io>
merceri<N-a>
merchandising<N-non>
mercimon<N-io>
mercur<N-io>
merd<N-a>
meridian<N-a>
meridional<N-e>
meridionalism<N-o>
merit<N-o>
meritocrazi<N-a>
messaggeri<N-a>
messagg<N-io>
messag<N-io>
messal<N-e>
mes<N-ta>
mestizi<N-a>
mestruaz<N-ione>
metaboli<N-ta>
metadon<N-e>
metafor<N-a>
metallar<N-o>
metall<N-o>
metalmeccanic<N-a>
meteorolo<N-gia>
meter<N-non>
metereolog<N-o>
meticolosi<N-tA>
metodic<N-a>
metodis<N-ta>
metod<N-o>
metodolo<N-gia>
metric<N-a>
metrò<N-non>
mezzadr<N-o>
mezzibust<N-o>
miagol<N-io>
mic<N-io>
micr<N-o>
microbiolog<N-o>
microscopic<N-o>
microscop<N-io>
microspi<N-a>
microstruttur<N-a>
microvettur<N-a>
migl<N-io>
mignol<N-o>
mignot<N-ta>
miliardari<N-a>
miliardar<N-io>
miliard<N-o>
milionar<N-io>
militanz<N-a>
milit<N-e>
millantator<N-e>
mill<N-e>
millenar<N-io>
millimetr<N-o>
milz<N-a>
mimetizzaz<N-ione>
mimic<N-a>
mim<N-o>
minaccia<N-ta>
minaret<N-o>
mineral<N-e>
minestron<N-e>
mini-rifor<N-ma>
miniappartament<N-o>
miniaturizzaz<N-ione>
minibus<N-non>
minicomputer<N-non>
minier<N-a>
minimalism<N-o>
minimum-tax<N-non>
minister<N-o>
minorat<N-o>
minorenn<N-e>
minuett<N-o>
minu<N-ta>
miopi<N-a>
miriad<N-e>
miscel<N-a>
mischi<N-a>
miscredent<N-e>
misfatt<N-o>
missagg<N-io>
missil<N-e>
missionar<N-io>
miss<N-ione>
mis<N-ta>
mistic<N-a>
misticism<N-o>
mistur<N-a>
misur<N-a>
misuraz<N-ione>
mitic<N-a>
mitizzaz<N-ione>
mitragliator<N-e>
mitragliatric<N-e>
mitraglier<N-e>
mitterrandism<N-o>
mobil<N-e>
mobilett<N-o>
mobilier<N-e>
mobilific<N-io>
mobil<N-io>
mobili<N-tA>
mocassin<N-o>
moccol<N-o>
modali<N-tA>
modell<N-a>
modem<N-non>
moderat<N-o>
moderni<N-tA>
modernizzator<N-e>
modificaz<N-ione>
modis<N-ta>
modulaz<N-ione>
modul<N-o>
mogan<N-o>
mogliettin<N-a>
moin<N-a>
molestator<N-e>
moll<N-e>
mollet<N-ta>
mollezz<N-a>
mollusc<N-o>
molteplici<N-tA>
moment<N-o>
monad<N-e>
monaster<N-o>
mondializzaz<N-ione>
mond<N-o>
mone<N-ta>
monetarism<N-o>
monetin<N-a>
monitoragg<N-io>
monocolor<N-e>
monolocal<N-e>
monopol<N-io>
monopost<N-o>
monoscaf<N-o>
monotip<N-o>
monovolum<N-e>
monson<N-e>
montagn<N-a>
montanar<N-o>
mont<N-e>
monton<N-e>
monumentali<N-tA>
monument<N-o>
monzes<N-e>
moquett<N-e>
mor<N-a>
moral<N-e>
moralizzator<N-e>
moralizzaz<N-ione>
moratori<N-a>
mordent<N-e>
mormor<N-io>
mor<N-o>
mors<N-o>
mortadell<N-a>
mortal<N-e>
mortali<N-tA>
mortarett<N-o>
mort<N-o>
moschettier<N-e>
moschetton<N-e>
moscovi<N-ta>
most<N-o>
mostr<N-a>
mostriciattol<N-o>
mostr<N-o>
motiv<N-o>
mot<N-o>
motocarr<N-o>
motocicl<N-o>
motomondial<N-e>
motorin<N-o>
motoseg<N-a>
motric<N-e>
mous<N-e>
movenz<N-a>
moviment<N-o>
mozambican<N-o>
moz<N-ione>
mozzarell<N-a>
mozz<N-o>
mucchiett<N-o>
mucch<N-io>
mucillaggin<N-e>
muc<N-o>
muflon<N-e>
mugol<N-io>
mulat<N-ta>
mulatt<N-o>
mul<N-ta>
multiculturalism<N-o>
multimedi<N-a>
multimediali<N-tA>
multimiliardar<N-io>
multinazional<N-e>
multipartitism<N-o>
multiproprietar<N-io>
multiproprie<N-tA>
mundial<N-non>
mungitric<N-e>
municipali<N-tA>
muon<N-e>
muragl<N-ione>
muratur<N-a>
musch<N-io>
musett<N-o>
music<N-a>
musicali<N-tA>
musicasset<N-ta>
music<N-o>
musin<N-o>
mussulman<N-o>
must<N-non>
mutandin<N-a>
mutuali<N-tA>
mutu<N-o>
mystery<N-non>
métr<N-o>
naf<N-ta>
naif<N-non>
napp<N-a>
narcisis<N-ta>
narrativ<N-a>
narrator<N-e>
narratric<N-e>
nascitur<N-a>
nascondigl<N-io>
nascondiment<N-o>
nasin<N-o>
nason<N-e>
nativ<N-o>
nat<N-o>
natur<N-a>
naturalis<N-ta>
nava<N-ta>
navicell<N-a>
navigant<N-e>
navigaz<N-ione>
navigl<N-io>
naz<N-ione>
nebb<N-ione>
nefandezz<N-a>
nefas<N-ta>
nefast<N-o>
negativ<N-o>
negator<N-e>
negligenz<N-a>
negoziat<N-o>
negoziett<N-o>
negrett<N-o>
negr<N-o>
nemb<N-o>
neni<N-a>
ne<N-o>
neo-direttor<N-e>
neo-elett<N-o>
neo-gollis<N-ta>
neo-laureat<N-o>
neo-mam<N-ma>
neo-nazis<N-ta>
neo-president<N-e>
neoacquist<N-o>
neoclassic<N-o>
neocomunis<N-ta>
neodirettor<N-e>
neoliberism<N-o>
neoministr<N-o>
neonat<N-o>
neopresident<N-e>
neosindac<N-o>
neospos<N-o>
nepales<N-e>
nerborut<N-o>
network<N-non>
neurobiolog<N-o>
neurofisiolog<N-o>
neuropsichiatr<N-a>
neurotrasmettitor<N-e>
neutralism<N-o>
nevica<N-ta>
nevral<N-gia>
nevros<N-i>
newyorkes<N-e>
nigerian<N-o>
night<N-non>
night-club<N-non>
nipot<N-e>
nipponic<N-o>
nitrat<N-o>
nobiluom<N-o>
nocchier<N-o>
nocciolin<N-a>
nocciol<N-o>
nod<N-o>
noir<N-non>
nomadism<N-o>
nomi<N-ma>
nomin<N-a>
nominativi<N-tA>
nominativ<N-o>
non-violenz<N-a>
non-vot<N-o>
noncuranz<N-a>
nonnett<N-o>
nonn<N-o>
nordic<N-a>
nordirlandes<N-e>
nor<N-ma>
normalizzaz<N-ione>
nostal<N-gia>
nostalgic<N-o>
nostran<N-o>
no<N-ta>
nota<N-io>
notaz<N-ione>
notes<N-non>
notificaz<N-ione>
notizi<N-a>
notiziol<N-a>
nottambul<N-o>
nott<N-e>
notturn<N-o>
novantin<N-a>
novares<N-e>
novell<N-a>
novell<N-o>
noven<N-a>
nover<N-o>
novi<N-tA>
novizi<N-a>
noviziat<N-o>
nuc<N-a>
nud<N-o>
nugol<N-o>
nullafacent<N-e>
nullatenent<N-e>
num<N-e>
numeraz<N-ione>
numerett<N-o>
nuor<N-a>
nuot<N-o>
nuragh<N-e>
nursery<N-non>
nutriment<N-o>
nuvolet<N-ta>
nuvolon<N-e>
nylon<N-non>
obbedienz<N-a>
obbiez<N-ione>
obbligazionis<N-ta>
obblig<N-o>
obic<N-e>
obiez<N-ione>
occasional<N-e>
occhettian<N-o>
occh<N-io>
occhiolin<N-o>
occh<N-ione>
oculatezz<N-a>
od<N-e>
od<N-io>
odios<N-o>
odontoiatr<N-a>
offensiv<N-a>
oggettivi<N-tA>
oggett<N-o>
ogg<N-i>
ol<N-a>
oleific<N-io>
oleodott<N-o>
oligopol<N-io>
olm<N-o>
olocaust<N-o>
oltranzism<N-o>
oltranzis<N-ta>
omagg<N-io>
ombelic<N-o>
ombrellin<N-o>
omin<N-o>
omogenei<N-tA>
omogeneizzaz<N-ione>
omologaz<N-ione>
omolog<N-o>
omon<N-e>
omonim<N-o>
omosessual<N-e>
omuncol<N-o>
oncolo<N-gia>
onda<N-ta>
onest<N-o>
opaci<N-tA>
operai<N-a>
opera<N-io>
operat<N-o>
operator<N-e>
operaz<N-ione>
operet<N-ta>
opinionis<N-ta>
opportunism<N-o>
opportunis<N-ta>
opportuni<N-tA>
opulent<N-o>
orator<N-e>
oratori<N-a>
orator<N-io>
orchestr<N-a>
ordinament<N-o>
ordinari<N-a>
ordinativ<N-o>
ordinaz<N-ione>
orecchin<N-o>
orefic<N-e>
oreficeri<N-a>
orfanell<N-a>
organett<N-o>
organis<N-ta>
organizzator<N-e>
organizzaz<N-ione>
orgasm<N-o>
or<N-gia>
orgin<N-e>
orientalism<N-o>
orient<N-e>
original<N-e>
originar<N-io>
origin<N-e>
or<N-ma>
ormon<N-e>
orolog<N-io>
oroscop<N-o>
orrend<N-o>
orror<N-e>
ors<N-o>
ort<N-o>
ortodoss<N-a>
ortodossi<N-a>
osceni<N-tA>
oscillaz<N-ione>
osmos<N-i>
ospitali<N-tA>
ospiz<N-io>
ossatur<N-a>
ossequ<N-io>
osservanz<N-a>
osservator<N-io>
ossess<N-o>
ossid<N-o>
ossigen<N-o>
ostacol<N-o>
ostetric<N-o>
osti<N-a>
ostinat<N-o>
ostinaz<N-ione>
otit<N-e>
ottantin<N-a>
ottav<N-a>
ottic<N-a>
ottimism<N-o>
ottim<N-o>
ottuagenar<N-io>
ottusi<N-tA>
oval<N-e>
overdos<N-e>
ovvie<N-tA>
ovv<N-io>
pacc<N-a>
pacchett<N-o>
pacc<N-o>
paccottigli<N-a>
pac<N-e>
pachistan<N-o>
pacier<N-e>
pacific<N-a>
pacific<N-o>
pacifis<N-ta>
padan<N-o>
padretern<N-o>
paesagg<N-io>
paes<N-e>
paeson<N-e>
paganesim<N-o>
pag<N-e>
paggett<N-o>
paginet<N-ta>
pagli<N-a>
pagliaccia<N-ta>
paglia<N-io>
pagliericc<N-io>
pal<N-a>
palafit<N-ta>
palazzinar<N-o>
palazzon<N-e>
palc<N-o>
palcoscenic<N-o>
paleoantropolog<N-o>
palestr<N-a>
palingenes<N-i>
palinsest<N-o>
palla-gol<N-non>
pallacanestr<N-o>
pallavolis<N-ta>
pallin<N-a>
pallin<N-o>
pallona<N-ta>
palloncin<N-o>
pallottol<N-a>
pallottolier<N-e>
palmarès<N-non>
palmiz<N-io>
pal<N-o>
palpeggiament<N-o>
pamp<N-a>
panace<N-a>
pancet<N-ta>
pan<N-cia>
pancreas<N-non>
pand<N-a>
pandemon<N-io>
panel<N-non>
panetton<N-e>
panfil<N-o>
pani<N-a>
panier<N-e>
panific<N-io>
panin<N-o>
paninotec<N-a>
pannell<N-o>
pannocchi<N-a>
pantegan<N-a>
panter<N-a>
pantofol<N-a>
panzan<N-a>
pap<N-a>
paparazz<N-o>
papat<N-o>
papaver<N-o>
paper<N-a>
paperback<N-non>
pappon<N-e>
parabol<N-a>
parabolic<N-a>
parabrezz<N-a>
paracadutis<N-ta>
paradig<N-ma>
paradis<N-o>
parafang<N-o>
paragraf<N-o>
paraguayan<N-o>
paralis<N-i>
parallel<N-a>
parallel<N-o>
paralum<N-e>
parament<N-o>
paramilitar<N-e>
paranormal<N-e>
paraocch<N-i>
paraplegic<N-o>
parapsicolo<N-gia>
parassi<N-ta>
parassitism<N-o>
parcellizzaz<N-ione>
parc<N-o>
paregg<N-io>
parentel<N-a>
pari<N-a>
parificaz<N-ione>
parlament<N-o>
parlantin<N-a>
parlator<N-io>
parmens<N-e>
parol<N-a>
parossism<N-o>
parquet<N-non>
parrocchian<N-a>
parrucc<N-a>
parrucchier<N-a>
parrucchin<N-o>
parsimoni<N-a>
part-tim<N-e>
partenope<N-o>
partent<N-e>
particin<N-a>
particolarism<N-o>
particolari<N-tA>
partit<N-o>
partito-stat<N-o>
partitocrazi<N-a>
partiton<N-e>
partitur<N-a>
partiz<N-ione>
partner<N-non>
part<N-o>
party<N-non>
parziali<N-tA>
parà<N-non>
passagg<N-io>
passant<N-e>
passatemp<N-o>
passatis<N-ta>
passat<N-o>
passator<N-e>
passegger<N-o>
passeggin<N-o>
passepartout<N-non>
passerell<N-a>
passiv<N-o>
pasta<N-io>
pastasciut<N-ta>
pasticcer<N-e>
pasticciacc<N-io>
pasticc<N-io>
past<N-o>
pastorelleri<N-a>
pastorell<N-o>
pastorizi<N-a>
pastrocch<N-io>
pata<N-ta>
patchwork<N-non>
patentin<N-o>
patetic<N-a>
pathos<N-non>
patibol<N-o>
patolog<N-o>
patriarcat<N-o>
patrign<N-o>
patrimon<N-io>
patrio<N-ta>
patriottism<N-o>
patriz<N-io>
patrocin<N-io>
patron<N-a>
patron<N-o>
pat<N-ta>
patteggiament<N-o>
pattinagg<N-io>
pattinator<N-e>
pattugliament<N-o>
pattugl<N-ione>
pattuiz<N-ione>
paves<N-e>
pavimentaz<N-ione>
paviment<N-o>
pavè<N-non>
pavé<N-non>
pax<N-non>
pazienz<N-a>
paìs<N-non>
pc<N-i>
pean<N-a>
pecc<N-a>
peccatric<N-e>
pechines<N-e>
peculat<N-o>
peculiari<N-tA>
pedagg<N-io>
pedalator<N-e>
pedal<N-e>
pedanteri<N-a>
pederas<N-ta>
pediatr<N-a>
pedinament<N-o>
peeling<N-non>
peggiorament<N-o>
peggior<N-e>
pegn<N-o>
pellegrin<N-o>
pelleross<N-a>
pelliccia<N-io>
pen<N-a>
penalis<N-ta>
penali<N-tA>
penalizzaz<N-ione>
pendenz<N-a>
pendic<N-e>
pendol<N-a>
pendolin<N-o>
pendol<N-o>
pen<N-e>
penitent<N-e>
penitenz<N-a>
penn<N-a>
pennivendol<N-o>
pensa<N-ta>
pensato<N-io>
pensator<N-e>
pensierin<N-o>
pensier<N-o>
pensionament<N-o>
pensionant<N-e>
pensionat<N-o>
pentol<N-a>
penulti<N-ma>
penultim<N-o>
peon<N-e>
peoni<N-a>
pep<N-e>
percom<N-e>
percors<N-o>
percuss<N-ione>
percussionis<N-ta>
perdigiorn<N-o>
perdi<N-ta>
perdiz<N-ione>
perdonism<N-o>
perdurant<N-e>
peregrinaz<N-ione>
perestroik<N-a>
perfezionament<N-o>
perfid<N-a>
performanc<N-e>
performer<N-non>
pergamen<N-a>
pericol<N-o>
periferic<N-a>
periodic<N-o>
period<N-o>
perit<N-o>
perizi<N-a>
permu<N-ta>
pern<N-o>
pernottament<N-o>
peronism<N-o>
perpless<N-o>
perseguitat<N-o>
perseveranz<N-a>
persian<N-o>
personagg<N-io>
personaggio-chiav<N-e>
personali<N-tA>
personalizzaz<N-ione>
personificaz<N-ione>
persuas<N-ione>
persuasor<N-e>
perticon<N-e>
pertoss<N-e>
pertug<N-io>
perugin<N-o>
peruvian<N-a>
peruvian<N-o>
pervers<N-a>
pervica<N-cia>
pesantezz<N-a>
pesares<N-e>
pescares<N-e>
pesc<N-e>
pescherecc<N-io>
pescheri<N-a>
pes<N-o>
pesos<N-non>
pessimis<N-ta>
pest<N-e>
pesticid<N-a>
peston<N-e>
petal<N-o>
petard<N-o>
petrodollar<N-o>
petrolchimic<N-a>
petrolchimic<N-o>
petrol<N-io>
pettegolezz<N-o>
petulanz<N-a>
pezzatur<N-a>
pg<N-non>
piagniste<N-o>
pianal<N-e>
pianerottol<N-o>
piane<N-ta>
pianificaz<N-ione>
pian<N-o>
piano-bar<N-non>
pianobar<N-non>
piantator<N-e>
pianterren<N-o>
piantin<N-a>
pianton<N-e>
piastr<N-a>
piat<N-ta>
piattezz<N-a>
piatt<N-o>
piazzal<N-e>
piazzament<N-o>
piazzat<N-o>
piazzet<N-ta>
piazzol<N-a>
picar<N-o>
picchiator<N-e>
piccin<N-a>
piccineri<N-a>
picciol<N-o>
picc<N-ione>
picciott<N-o>
piccolett<N-o>
piccolin<N-a>
piccol<N-o>
piccona<N-ta>
pick<N-non>
pick-up<N-non>
pickup<N-non>
pidiessin<N-o>
piec<N-e>
piedestall<N-o>
piedon<N-e>
piegament<N-o>
pienezz<N-a>
piercing<N-non>
pietism<N-o>
pietrai<N-a>
pietruzz<N-a>
pie<N-tA>
piev<N-e>
piffera<N-io>
pigia<N-ma>
pigl<N-io>
pignoleri<N-a>
pigrizi<N-a>
pigr<N-o>
pilastr<N-o>
pilo<N-ta>
pin-up<N-non>
pine<N-ta>
ping<N-non>
ping-pong<N-non>
pin<N-o>
pinz<N-a>
p<N-io>
pionier<N-a>
pioppet<N-o>
pir<N-a>
piroscaf<N-o>
piscin<N-a>
pis<N-ta>
pistacch<N-io>
pistoies<N-e>
pistol<N-a>
pistoletta<N-ta>
piston<N-e>
pittoresc<N-a>
piu<N-ma>
piumagg<N-io>
piumin<N-o>
piumon<N-e>
pivell<N-o>
pivot<N-non>
pizz<N-a>
pizzicott<N-o>
pièc<N-e>
placcagg<N-io>
placchet<N-ta>
placen<N-ta>
plag<N-a>
plaid<N-non>
plana<N-ta>
plan<N-cia>
planetar<N-io>
planetolog<N-o>
planimetri<N-a>
plantar<N-e>
plas<N-ma>
plastici<N-tA>
plastic<N-o>
playmaker<N-non>
plaz<N-a>
plot<N-non>
plural<N-e>
pluralism<N-o>
plurimiliardar<N-io>
pluripartitism<N-o>
pluton<N-io>
pneumatic<N-o>
pnl<N-non>
pocket<N-non>
podis<N-ta>
poemett<N-o>
poe<N-ta>
poetess<N-a>
poggiates<N-ta>
pogg<N-io>
pogrom<N-non>
polacc<N-o>
polarizzaz<N-ione>
polaroid<N-non>
polen<N-ta>
policlinic<N-o>
polietilen<N-e>
polifoni<N-a>
poligami<N-a>
poligrafic<N-o>
polimer<N-o>
polipropilen<N-e>
polisportiv<N-a>
polistirol<N-o>
politecnic<N-o>
politici<N-tA>
politolo<N-gia>
poliuretan<N-o>
poliziesc<N-o>
poliziot<N-ta>
polizz<N-a>
polk<N-a>
pollastr<N-o>
pollin<N-e>
poll<N-o>
polluz<N-ione>
polmon<N-e>
polp<N-a>
polpastrell<N-o>
polpetton<N-e>
polp<N-o>
polsin<N-o>
poltroncin<N-a>
polver<N-e>
pomell<N-o>
pomeridian<N-a>
pomodor<N-o>
pomposi<N-tA>
ponderaz<N-ione>
ponent<N-e>
pontegg<N-io>
pontil<N-e>
ponton<N-e>
pool<N-non>
popolan<N-a>
popolan<N-o>
popolarism<N-o>
popolari<N-tA>
popol<N-o>
porcellin<N-o>
porcell<N-o>
porcheri<N-a>
porc<N-o>
pordenones<N-e>
pornodiv<N-a>
pornofilm<N-non>
pornografi<N-a>
pornograf<N-o>
portabagagl<N-i>
portacener<N-e>
portal<N-e>
portament<N-o>
portantin<N-o>
portapacch<N-i>
porta<N-ta>
portatil<N-e>
portavoc<N-e>
portent<N-o>
porticat<N-o>
porticciol<N-o>
porticin<N-a>
portic<N-o>
portinai<N-a>
portineri<N-a>
porz<N-ione>
pos<N-a>
positivi<N-tA>
posizionament<N-o>
possessor<N-e>
possibli<N-tA>
postaz<N-ione>
postfaz<N-ione>
posticin<N-o>
postin<N-a>
postribol<N-o>
potent<N-e>
potenz<N-a>
potes<N-tA>
pourparler<N-non>
poveret<N-ta>
poverett<N-o>
pover<N-o>
pover<N-tA>
pozz<N-a>
pr<N-non>
pranz<N-o>
praticant<N-e>
praticell<N-o>
pratici<N-tA>
pre-accord<N-o>
pre-requisit<N-o>
preallarm<N-e>
preambol<N-o>
precampionat<N-o>
precarie<N-tA>
precar<N-io>
precauz<N-ione>
precettor<N-e>
precipitaz<N-ione>
precipiz<N-io>
precisaz<N-ione>
preclus<N-ione>
precongress<N-o>
preconsuntiv<N-o>
precott<N-o>
pred<N-a>
predecessor<N-e>
predell<N-a>
predet<N-ta>
predett<N-o>
predicator<N-e>
predicaz<N-ione>
predisposiz<N-ione>
predominanz<N-a>
predomin<N-io>
prefaz<N-ione>
preferenz<N-a>
prefiss<N-o>
preghier<N-a>
pregiudicat<N-o>
pregiudiz<N-io>
pregnanz<N-a>
prelat<N-o>
preliminar<N-e>
premeditaz<N-ione>
premess<N-a>
prem<N-io>
prenditor<N-e>
preoccupaz<N-ione>
prepensionament<N-o>
prepensionat<N-o>
preposiz<N-ione>
prepotenz<N-a>
pres<N-a>
presag<N-io>
prescriz<N-ione>
presentator<N-e>
presentaz<N-ione>
presep<N-io>
preservaz<N-ione>
presidentess<N-a>
presidenzialis<N-ta>
pressappochism<N-o>
press<N-i>
pressing<N-non>
prestanz<N-a>
prestaz<N-ione>
prestig<N-io>
prestit<N-o>
presunz<N-ione>
pretor<N-e>
prevaricator<N-e>
prevendi<N-ta>
preventiv<N-o>
prevenz<N-ione>
previdenz<N-a>
previson<N-e>
preziosism<N-o>
prigioner<N-o>
prigionier<N-o>
primadonn<N-a>
primatis<N-ta>
primat<N-o>
primattor<N-e>
primavera-estat<N-e>
primitiv<N-a>
primitivism<N-o>
principessin<N-a>
princìp<N-io>
privatizzator<N-e>
privat<N-o>
privé<N-non>
probabili<N-tA>
probi<N-tA>
probovir<N-o>
procacciator<N-e>
proccupaz<N-ione>
procedur<N-a>
process<N-o>
processon<N-e>
processor<N-e>
procla<N-ma>
procreaz<N-ione>
prodian<N-o>
prodig<N-io>
produttivi<N-tA>
produttor<N-e>
profanator<N-e>
profanaz<N-ione>
profan<N-o>
profess<N-ione>
professionis<N-ta>
professor<N-e>
professorin<N-o>
professoron<N-e>
profitt<N-o>
profluv<N-io>
profondi<N-tA>
profond<N-o>
profug<N-a>
profumeri<N-a>
profum<N-o>
progenitric<N-e>
progettis<N-ta>
progett<N-o>
prognos<N-i>
progra<N-ma>
program<N-ma>
programm<N-ma>
progress<N-ione>
progressivi<N-tA>
proibit<N-o>
proibizionism<N-o>
proiettil<N-e>
proiez<N-ione>
prolific<N-o>
promiscui<N-tA>
prom<N-o>
promotion<N-non>
promotor<N-e>
promotric<N-e>
promulgaz<N-ione>
pronipot<N-e>
prontezz<N-a>
prontuar<N-io>
propagand<N-a>
propaggin<N-e>
propens<N-ione>
propos<N-ta>
proprie<N-tA>
prorogat<N-io>
prosciutt<N-o>
prospettaz<N-ione>
prospett<N-o>
prossimi<N-tA>
prostaglandin<N-a>
prostitu<N-ta>
prostituz<N-ione>
prostraz<N-ione>
protagonis<N-ta>
proteas<N-i>
protes<N-ta>
protest<N-o>
protettorat<N-o>
protez<N-ione>
prototip<N-o>
provediment<N-o>
provenienz<N-a>
provet<N-ta>
provider<N-non>
provincial<N-e>
provincialism<N-o>
provvediment<N-o>
provveditor<N-e>
provvidenz<N-a>
provvisional<N-e>
provvis<N-ta>
prudenz<N-a>
prurit<N-o>
prìncip<N-e>
pseudonim<N-o>
psichiatr<N-a>
psichiatri<N-a>
psicoanalis<N-ta>
psicofarmac<N-o>
psicolog<N-a>
psicolog<N-o>
psicoterapi<N-a>
pubal<N-gia>
pubblicaz<N-ione>
pubblicis<N-ta>
pubblici<N-tA>
pubblicizzaz<N-ione>
puber<N-tA>
pugil<N-e>
puglies<N-e>
pugnala<N-ta>
pugn<N-o>
pulc<N-e>
puledr<N-o>
puli<N-ta>
pulit<N-o>
pullmin<N-o>
pulmann<N-non>
pulmin<N-o>
pulviscol<N-o>
pungol<N-o>
puniz<N-ione>
punticin<N-o>
puntigliosi<N-tA>
puntin<N-a>
punto-chiav<N-e>
puntualizzaz<N-ione>
punzecchiatur<N-a>
pupazz<N-o>
pupazzon<N-e>
pupill<N-o>
pup<N-o>
purificaz<N-ione>
purism<N-o>
puris<N-ta>
puttana<N-ta>
puttanon<N-a>
puttin<N-o>
putt<N-o>
puzz<N-a>
quaccher<N-o>
quadernett<N-o>
quadrant<N-e>
quadrett<N-o>
quadrienn<N-io>
quadrilater<N-o>
quadrimotor<N-e>
quadripartit<N-o>
quadrumvir<N-o>
quadruplicament<N-o>
quagli<N-a>
quali<N-tA>
qualunquis<N-ta>
quantum<N-non>
quarantennal<N-e>
quartin<N-a>
quarz<N-o>
quattrocentis<N-ta>
querel<N-a>
querelant<N-e>
questionar<N-io>
questur<N-a>
quindicenn<N-e>
quindicinal<N-e>
quin<N-ta>
quintal<N-e>
quintessenz<N-a>
quintett<N-o>
quotidiani<N-tA>
rabbuff<N-o>
rabdomant<N-e>
raccattapall<N-e>
raccogliment<N-o>
raccoglitor<N-e>
raccomandaz<N-ione>
radar<N-non>
radicalizzaz<N-ione>
radioascoltator<N-e>
radiodram<N-ma>
radiogiornal<N-e>
radiolin<N-a>
radiolog<N-o>
radiomicrofon<N-o>
radioterapi<N-a>
radur<N-a>
raffiguraz<N-ione>
raffina<N-ta>
raffinat<N-o>
raffineri<N-a>
raffreddament<N-o>
raffront<N-o>
ragazzacc<N-io>
ragazza<N-ta>
ragazzett<N-o>
ragazzon<N-e>
ragg<N-io>
raggir<N-o>
ragionament<N-o>
rag<N-ione>
ragioneri<N-a>
ragionevolezz<N-a>
ragnatel<N-a>
ragn<N-o>
raider<N-non>
rail<N-non>
rais<N-non>
ralent<N-i>
ramanzin<N-a>
ramazz<N-a>
ram<N-e>
ram<N-o>
ramp<N-a>
rampant<N-e>
rampin<N-o>
rampon<N-e>
ran<N-a>
randag<N-io>
randella<N-ta>
randell<N-o>
rang<N-o>
ranking<N-non>
rantol<N-o>
rapidi<N-tA>
rapin<N-a>
rapinat<N-o>
rapinator<N-e>
rappacificaz<N-ione>
rappresentant<N-e>
rar<N-o>
rasoterr<N-a>
rassegn<N-a>
rassegnaz<N-ione>
rasserenament<N-o>
rassicuraz<N-ione>
rassomiglianz<N-a>
rastrellator<N-e>
rateizzaz<N-ione>
rating<N-non>
rat<N-io>
ravennat<N-e>
raziocin<N-io>
razionalism<N-o>
razionalis<N-ta>
razionalizzaz<N-ione>
razionament<N-o>
raz<N-ione>
razz<N-a>
razzi<N-a>
razzis<N-ta>
razz<N-o>
r<N-e>
realism<N-o>
realizzabili<N-tA>
realizzaz<N-ione>
realizz<N-o>
realpolitik<N-non>
ream<N-e>
reaz<N-ione>
recapit<N-o>
recess<N-o>
recettor<N-e>
recint<N-o>
recitaz<N-ione>
reclam<N-o>
reclus<N-o>
reclusor<N-io>
reclu<N-ta>
recordman<N-non>
recriminaz<N-ione>
recrudescenz<N-a>
recuper<N-o>
redattor<N-e>
redditometr<N-o>
rediviv<N-o>
referedum<N-non>
referenz<N-a>
refettor<N-io>
refol<N-o>
regalin<N-o>
regali<N-tA>
reg<N-gia>
reggiment<N-o>
reggipett<N-o>
reggisen<N-o>
re<N-gia>
regin<N-a>
reginet<N-ta>
regionalism<N-o>
regolari<N-tA>
regolarizzaz<N-ione>
reindustrializzaz<N-ione>
reingress<N-o>
reintegr<N-o>
reintroduz<N-ione>
relais<N-non>
relator<N-e>
relatric<N-e>
relaz<N-ione>
reliqui<N-a>
reliquiar<N-io>
remator<N-e>
remiss<N-ione>
remissivi<N-tA>
remuneraz<N-ione>
rendez-vous<N-non>
rendiment<N-o>
renitenz<N-a>
rentré<N-e>
repert<N-o>
repertor<N-io>
replicant<N-e>
replicaz<N-ione>
reporter<N-non>
repress<N-o>
reprimend<N-a>
repubblic<N-a>
repubblichin<N-o>
resciss<N-ione>
residu<N-o>
resin<N-a>
respin<N-ta>
respirator<N-e>
respir<N-o>
responsabili<N-tA>
responsabil<N-tA>
resposabili<N-tA>
restauratric<N-e>
restaur<N-o>
rest<N-o>
restriz<N-ione>
reticell<N-a>
reticol<N-o>
retin<N-o>
retribuz<N-ione>
retrocess<N-ione>
retroguardi<N-a>
retromar<N-cia>
retropalc<N-o>
retropassagg<N-io>
retrovirus<N-non>
retrovisor<N-e>
rettangolin<N-o>
rettitudin<N-e>
reumatism<N-o>
revival<N-non>
revolver<N-non>
riabilitaz<N-ione>
riaccorpament<N-o>
riacquist<N-o>
riaggiustament<N-o>
rialzis<N-ta>
rialz<N-o>
rianimator<N-e>
riapertur<N-a>
riappariz<N-ione>
riappropriaz<N-ione>
riarm<N-o>
riassicuraz<N-ione>
riassunt<N-o>
riassunz<N-ione>
riavvicinament<N-o>
ribell<N-e>
ribilanciament<N-o>
ricadu<N-ta>
ricalc<N-o>
ricalcol<N-o>
ricamator<N-e>
ricapitalizzaz<N-ione>
ricapitolaz<N-ione>
ricaric<N-a>
ricav<N-o>
ricc<N-io>
ricciolett<N-o>
ricciolon<N-e>
ricc<N-o>
ricercatezz<N-a>
ricercator<N-e>
ricet<N-ta>
ricettaz<N-ione>
ricettivi<N-tA>
ricevitor<N-e>
ricevu<N-ta>
richiam<N-o>
riciclagg<N-io>
riclassificaz<N-ione>
ricompars<N-a>
ricompattament<N-o>
ricompens<N-a>
ricomposiz<N-ione>
riconciliaz<N-ione>
riconfermat<N-o>
riconoscenz<N-a>
riconsegn<N-a>
riconsideraz<N-ione>
ricopertur<N-a>
ricord<N-o>
ricors<N-o>
ricostruz<N-ione>
ricreaz<N-ione>
ridimensionament<N-o>
ridipintur<N-a>
riduttor<N-e>
riduzionism<N-o>
riediz<N-ione>
rielaboraz<N-ione>
rielez<N-ione>
riempitiv<N-o>
riesumaz<N-ione>
rievocaz<N-ione>
riff<N-non>
rifinanziament<N-o>
rifinitur<N-a>
rifiut<N-o>
rifless<N-ione>
riflettor<N-e>
rifondarol<N-o>
rifondaz<N-ione>
rifor<N-ma>
riformator<N-e>
riformism<N-o>
rifug<N-io>
rig<N-a>
rigett<N-o>
rigidezz<N-a>
rigidi<N-tA>
rig<N-o>
rigogl<N-io>
rigonfiament<N-o>
rigor<N-e>
rigoris<N-ta>
rigurgit<N-o>
rilascia<N-ta>
rilassament<N-o>
rilassatezz<N-a>
rilegatur<N-a>
rilevament<N-o>
rilevator<N-e>
rilevaz<N-ione>
rimandat<N-o>
rimanent<N-e>
rimanenz<N-a>
rimbalz<N-o>
rimbomb<N-o>
rimbrott<N-o>
rimembranz<N-a>
rimess<N-a>
rimodulaz<N-ione>
rimon<N-ta>
rimorch<N-io>
rimoss<N-o>
rimostranz<N-a>
rimoz<N-ione>
rimpiazz<N-o>
rinasci<N-ta>
rina<N-ta>
rinforz<N-o>
ringh<N-io>
ringraziament<N-o>
rinnegat<N-o>
rinnovament<N-o>
rinun<N-cia>
r<N-io>
riordin<N-o>
ripartiz<N-ione>
ripercuss<N-ione>
ripescagg<N-io>
ripetitor<N-e>
ripetiz<N-ione>
ripopolament<N-o>
riposin<N-o>
ripos<N-o>
ripres<N-a>
riproduz<N-ione>
riproposiz<N-ione>
riprovaz<N-ione>
ripud<N-io>
ripulitur<N-a>
riquadr<N-o>
risai<N-a>
risali<N-ta>
risatac<N-cia>
risatin<N-a>
riscontr<N-o>
riscoper<N-ta>
risentiment<N-o>
riserv<N-a>
riservis<N-ta>
risonanz<N-a>
risors<N-a>
risort<N-o>
rispecchiament<N-o>
rispettabili<N-tA>
rispett<N-o>
rispondenz<N-a>
rispos<N-ta>
rissosi<N-tA>
ristabiliment<N-o>
ristagn<N-o>
ristorn<N-o>
ristor<N-o>
ristrett<N-o>
ristrutturaz<N-ione>
risulat<N-o>
risultanz<N-a>
risultat<N-o>
risurrez<N-ione>
risvegl<N-io>
risvolt<N-o>
ritenz<N-ione>
ritira<N-ta>
ritir<N-o>
ritm<N-o>
ritocc<N-o>
ritornant<N-e>
ritornell<N-o>
ritrattaz<N-ione>
rituali<N-tA>
riutilizz<N-o>
rivali<N-tA>
rivals<N-a>
rivalutaz<N-ione>
rivelator<N-e>
rivendicaz<N-ione>
rivol<N-o>
rivol<N-ta>
rivoluzionar<N-io>
rivoluz<N-ione>
roccafort<N-e>
rocchettar<N-o>
roc<N-cia>
rocc<N-ione>
rock<N-non>
rocker<N-non>
rog<N-gia>
rogn<N-a>
rog<N-o>
romanis<N-ta>
romanz<N-a>
romanzesc<N-o>
romanz<N-o>
romanzon<N-e>
romen<N-a>
romen<N-o>
rompicap<N-o>
rompighiacc<N-io>
rondin<N-e>
rosar<N-io>
ross<N-a>
rossett<N-o>
rossor<N-e>
rotai<N-a>
rot<N-ta>
rottamaz<N-ione>
rottam<N-e>
rottur<N-a>
roulett<N-e>
roulott<N-e>
round<N-non>
routin<N-e>
rovell<N-o>
rovesc<N-io>
rovin<N-a>
rov<N-o>
royalty<N-non>
rozzezz<N-a>
ruandes<N-e>
rubl<N-o>
ruder<N-e>
rudezz<N-a>
ruffian<N-o>
rugby<N-non>
ruggit<N-o>
rugiad<N-a>
rull<N-o>
rumen<N-o>
rumor<N-non>
rumorosi<N-tA>
ruol<N-o>
ruolo-chiav<N-e>
ruo<N-ta>
rusp<N-a>
russator<N-e>
ruvidezz<N-a>
sabat<N-o>
sabb<N-a>
sabotator<N-e>
sacc<N-o>
sadism<N-o>
sag<N-a>
saggezz<N-a>
sagg<N-io>
saggis<N-ta>
saldator<N-e>
sal<N-e>
salernitan<N-o>
saliscend<N-i>
sali<N-ta>
saliv<N-a>
salm<N-o>
salmonell<N-a>
saloon<N-non>
sals<N-a>
salsedin<N-e>
saltimbanc<N-o>
salum<N-e>
salut<N-o>
salv<N-a>
salvagent<N-e>
samb<N-a>
samovar<N-non>
sampdorian<N-o>
samura<N-i>
sanculott<N-o>
sanguign<N-o>
sanitar<N-io>
sanscrit<N-o>
san<N-ta>
santabarbar<N-a>
santificaz<N-ione>
santin<N-o>
sant<N-o>
santon<N-a>
santuar<N-io>
sapon<N-e>
saracinesc<N-a>
sardis<N-ta>
sar<N-i>
sarti<N-a>
sartori<N-a>
sassaiol<N-a>
sass<N-o>
sasson<N-e>
satanism<N-o>
satanis<N-ta>
satellit<N-e>
satellite-spi<N-a>
sax<N-non>
sbadataggin<N-e>
sbalordiment<N-o>
sbandament<N-o>
sbandat<N-o>
sbandierament<N-o>
sband<N-o>
sberleff<N-o>
sbigottiment<N-o>
sbigottit<N-o>
sbilanciament<N-o>
sblocc<N-o>
sbocc<N-o>
sbronz<N-a>
sbuff<N-o>
scacchier<N-a>
scacchis<N-ta>
scadiment<N-o>
scafandr<N-o>
scaffalatur<N-a>
scafis<N-ta>
scagli<N-a>
scagl<N-ione>
scala<N-ta>
scalator<N-e>
scale<N-a>
scalfittur<N-a>
scalina<N-ta>
scalin<N-o>
scalpellin<N-o>
scalp<N-o>
scalpor<N-e>
scamp<N-o>
scampol<N-o>
scandagl<N-io>
scandalett<N-o>
scandenz<N-a>
scandinav<N-o>
scann<N-o>
scansi<N-a>
scans<N-ione>
scapol<N-o>
scappament<N-o>
scappatoi<N-a>
scarabe<N-o>
scaramuc<N-cia>
scarceraz<N-ione>
scaricator<N-e>
scarpin<N-o>
scarsi<N-tA>
scartin<N-a>
scartoffi<N-a>
scassinator<N-e>
scatenat<N-o>
scatol<N-a>
scatolet<N-ta>
scatolin<N-a>
scatolon<N-e>
scatt<N-o>
scavalcament<N-o>
scavator<N-e>
sceicc<N-o>
scenar<N-io>
sceneggia<N-ta>
sceneggiator<N-e>
scenet<N-ta>
scenografi<N-a>
scetticism<N-o>
scettr<N-o>
sched<N-a>
scheletr<N-o>
schematism<N-o>
schematizzaz<N-ione>
schemin<N-o>
scher<N-ma>
schermagli<N-a>
schermidor<N-e>
schermitor<N-e>
scherzett<N-o>
scherz<N-o>
schiaccia<N-ta>
schiaff<N-o>
schiaffon<N-e>
schiant<N-o>
schiapp<N-a>
schiari<N-ta>
schiat<N-ta>
schien<N-a>
schienal<N-e>
schier<N-a>
schiettezz<N-a>
schifezz<N-a>
schiocc<N-o>
schizofrenic<N-o>
sc<N-i>
s<N-cia>
sciacquon<N-e>
scialb<N-o>
scialupp<N-a>
sciaman<N-o>
sciarad<N-a>
sciarp<N-a>
scienzia<N-ta>
scienziat<N-o>
scimpanzè<N-non>
scimpanzé<N-non>
sciocchezz<N-a>
sciogliment<N-o>
sciovinism<N-o>
sciovinis<N-ta>
scipp<N-o>
scis<N-ma>
scocciator<N-e>
scocciatur<N-a>
scolaresc<N-a>
scolaret<N-ta>
scolar<N-o>
scommess<N-a>
scommettitor<N-e>
scomod<N-a>
scomodi<N-tA>
scomod<N-o>
scompartiment<N-o>
scompart<N-o>
scomposiz<N-ione>
sconc<N-io>
sconfess<N-ione>
sconfort<N-o>
scontentezz<N-a>
scont<N-o>
scontr<N-o>
scoop<N-non>
scoper<N-ta>
scoppiatur<N-a>
scoppiett<N-io>
scopp<N-io>
scoppol<N-a>
scorament<N-o>
scorc<N-io>
scor<N-e>
scorpaccia<N-ta>
scorp<N-ione>
scorpor<N-o>
scorrettezz<N-a>
scorrevolezz<N-a>
scorriment<N-o>
scor<N-ta>
scortesi<N-a>
scoss<N-a>
scostament<N-o>
scottatur<N-a>
scout<N-non>
scrann<N-o>
scrib<N-a>
scricchiol<N-io>
scrittor<N-e>
scrivani<N-a>
scrosc<N-io>
scrutator<N-e>
scuderi<N-a>
scud<N-o>
sculaccia<N-ta>
scultor<N-e>
scuol<N-a>
sdegn<N-o>
sdoganament<N-o>
sdoppiament<N-o>
secchia<N-ta>
secchiell<N-o>
secch<N-io>
secessionism<N-o>
secolarizzaz<N-ione>
secol<N-o>
second<N-a>
secondin<N-o>
second<N-o>
secrez<N-ione>
sed<N-e>
seder<N-e>
sedi<N-a>
sediolin<N-a>
sedu<N-ta>
seduttric<N-e>
seg<N-a>
segg<N-io>
seggiol<N-a>
segnalament<N-o>
segnal<N-e>
segnatur<N-a>
segretariat<N-o>
segreteri<N-a>
seguac<N-e>
seleziona<N-ta>
sellin<N-o>
selv<N-a>
selvaggin<N-a>
semiconduttor<N-e>
semid<N-io>
semilavorat<N-o>
seminator<N-e>
seminfermi<N-tA>
semiolog<N-o>
semioscuri<N-tA>
semiton<N-o>
semplicism<N-o>
semplificaz<N-ione>
senatùr<N-non>
senescenz<N-a>
senili<N-tA>
senn<N-o>
sen<N-o>
sensazionalism<N-o>
sensaz<N-ione>
sensibilizzaz<N-ione>
sentenza-ordinanz<N-a>
sentin<N-a>
separatezz<N-a>
sepolt<N-o>
sepoltur<N-a>
seppelliment<N-o>
sequel<N-a>
sequestr<N-i>
sequoi<N-a>
seracc<N-o>
sera<N-ta>
serbato<N-io>
serbo-bosniac<N-o>
serena<N-ta>
sereni<N-tA>
seriali<N-tA>
ser<N-io>
serpentin<N-a>
serpenton<N-e>
serrand<N-a>
servent<N-e>
server<N-non>
servic<N-e>
serviziett<N-o>
serviz<N-io>
sessantottin<N-o>
sess<N-ione>
sessuolog<N-o>
set<N-non>
set-point<N-non>
se<N-ta>
setacc<N-io>
set<N-e>
settantenn<N-io>
settiman<N-a>
settor<N-e>
severi<N-tA>
seviziator<N-e>
sex-shop<N-non>
sexy-shop<N-non>
sfaldament<N-o>
sfasament<N-o>
sfasc<N-io>
sfavor<N-e>
sfidant<N-e>
sfidu<N-cia>
sfig<N-a>
sfigat<N-o>
sfilz<N-a>
sfinter<N-e>
sfiz<N-io>
sfollagent<N-e>
sfollat<N-o>
sfoltiment<N-o>
sfortunat<N-o>
sfregament<N-o>
sfrenatezz<N-a>
sfruttator<N-e>
sgabuzzin<N-o>
sgambatur<N-a>
sganciament<N-o>
sgarb<N-o>
sgherr<N-o>
sghignazz<N-o>
sgobbon<N-e>
sgomber<N-o>
sgretolament<N-o>
sgrida<N-ta>
sgroppa<N-ta>
sguard<N-o>
shampo<N-o>
shari<N-a>
shopping<N-non>
shuttl<N-e>
siciliani<N-tA>
sicumer<N-a>
sicurezz<N-a>
sigarai<N-a>
sigaret<N-ta>
sigill<N-o>
significant<N-e>
significat<N-o>
signor<N-a>
signor<N-e>
signorin<N-a>
signorin<N-o>
sikh<N-non>
silenz<N-io>
silenzio-stamp<N-a>
silenziosi<N-tA>
sillab<N-a>
sillogism<N-o>
simbol<N-o>
simil<N-e>
similitudin<N-e>
simmetri<N-a>
simpati<N-a>
simpatic<N-o>
simpaticon<N-e>
simpos<N-io>
simultanei<N-tA>
sin<N-non>
sinaps<N-i>
sincretism<N-o>
sincronism<N-o>
sindacalis<N-ta>
sindacatin<N-o>
sindacat<N-o>
sindrom<N-e>
sinecur<N-a>
singales<N-e>
singolaris<N-ta>
singult<N-o>
sinistr<N-o>
sintetizzator<N-e>
sintom<N-o>
sintoni<N-a>
sinuosi<N-tA>
sipar<N-io>
siren<N-a>
sirian<N-o>
siring<N-a>
sis<N-ma>
sismograf<N-o>
siste<N-ma>
sistema-itali<N-a>
sistema-paes<N-e>
sistematici<N-tA>
sit-com<N-non>
sit-in<N-non>
situaz<N-ione>
skin<N-non>
slalom<N-non>
slalomis<N-ta>
slanc<N-io>
slavin<N-a>
slavis<N-ta>
slip<N-non>
slit<N-ta>
slittin<N-o>
smacc<N-o>
smantellament<N-o>
smargiassa<N-ta>
smarriment<N-o>
smarrit<N-o>
smemoratezz<N-a>
smistament<N-o>
smontagg<N-io>
smottament<N-o>
snellezz<N-a>
snobism<N-o>
sobrie<N-tA>
sobr<N-io>
soccorritor<N-e>
socialism<N-o>
socializzaz<N-ione>
sociobiolog<N-o>
sociolo<N-gia>
soddisfaz<N-ione>
sofferent<N-e>
soffiett<N-o>
sofis<N-ta>
sofistica<N-ta>
sofisticheri<N-a>
soggettivi<N-tA>
sogghign<N-o>
soggiornant<N-e>
soggiorn<N-o>
sogli<N-a>
sogliol<N-a>
soi<N-a>
sola<N-io>
solari<N-tA>
solarium<N-non>
soldatacc<N-io>
soldat<N-o>
solert<N-e>
solerzi<N-a>
solidarism<N-o>
solid<N-o>
solitar<N-io>
solit<N-o>
sollecitudin<N-e>
solleon<N-e>
sollevament<N-o>
sollevaz<N-ione>
solliev<N-o>
solon<N-e>
solvent<N-e>
somal<N-o>
somatizzaz<N-ione>
sommergibil<N-e>
sommess<N-o>
somministraz<N-ione>
somm<N-o>
sommoss<N-a>
sondaggis<N-ta>
sonnifer<N-o>
sonn<N-o>
sonnolenz<N-a>
sonori<N-tA>
sonor<N-o>
sontuosi<N-tA>
sopportabili<N-tA>
soppress<N-a>
soprabit<N-o>
sopraccigl<N-io>
soprannatural<N-e>
sopran<N-o>
soprattass<N-a>
sopravissut<N-o>
sopravvalutaz<N-ione>
sopravvenienz<N-a>
sopravvenut<N-o>
sopravvissu<N-ta>
sopravvivenz<N-a>
soprintendent<N-e>
soprintendenz<N-a>
sorc<N-io>
sordin<N-a>
sordi<N-tA>
sord<N-o>
sorell<N-a>
sorgent<N-e>
sorpass<N-o>
sort<N-e>
sortileg<N-io>
sorveglianz<N-a>
sos<N-non>
sospens<N-ione>
sos<N-ta>
sostenibili<N-tA>
sostrat<N-o>
sotterfug<N-io>
sottigliezz<N-a>
sottobosc<N-o>
sottocapitalizzaz<N-ione>
sottocorrent<N-e>
sottocultur<N-a>
sottopass<N-o>
sottoscritt<N-o>
sottosegretar<N-io>
sottospeci<N-e>
sottotett<N-o>
sottovalutaz<N-ione>
sovietic<N-a>
sovkhoz<N-non>
sovraffollament<N-o>
sovraintendent<N-e>
sovran<N-a>
sovrappopolaz<N-ione>
sovrapproduz<N-ione>
sovrastruttur<N-a>
sovrintendent<N-e>
sovvenzionament<N-o>
sovvers<N-ione>
sovversiv<N-o>
spad<N-a>
spadon<N-e>
spaghett<N-o>
spag<N-o>
spall<N-a>
spallet<N-ta>
sparegg<N-io>
spargiment<N-o>
spar<N-o>
spartit<N-o>
spartiz<N-ione>
spasimant<N-e>
spasm<N-o>
spauracch<N-io>
spavalderi<N-a>
spaventapasser<N-i>
spazzacamin<N-o>
spazzanev<N-e>
spazzatur<N-a>
spazzol<N-a>
spazzolin<N-o>
specchiett<N-o>
special<N-non>
specialis<N-ta>
specific<N-a>
speculari<N-tA>
speditezz<N-a>
spediz<N-ione>
spedizionier<N-e>
speechwriter<N-non>
spegniment<N-o>
spensieratezz<N-a>
spensierat<N-o>
sperequaz<N-ione>
spericolatezz<N-a>
spericolat<N-o>
sperimentator<N-e>
sper<N-ma>
speronament<N-o>
spes<N-a>
spessor<N-e>
spettacol<N-o>
spettacolon<N-e>
spettrometr<N-o>
spezzon<N-e>
spiag<N-gia>
spiana<N-ta>
spiazz<N-o>
spietatezz<N-a>
spiffer<N-o>
spig<N-a>
spigolatur<N-a>
spigolosi<N-tA>
spill<N-a>
spillet<N-ta>
spill<N-o>
spin<N-ta>
spioncin<N-o>
spiritell<N-o>
spiritosaggin<N-e>
spirituali<N-tA>
splendor<N-e>
split<N-non>
spogliarellis<N-ta>
spogliarell<N-o>
spogliato<N-io>
spoiler<N-non>
spoliaz<N-ione>
spolverin<N-o>
sponsor<N-non>
spontaneism<N-o>
spor<N-a>
sporcizi<N-a>
sporgenz<N-a>
sport<N-non>
sportivi<N-tA>
spossatezz<N-a>
spostament<N-o>
spot<N-non>
sprazz<N-o>
spread<N-non>
sproporz<N-ione>
sproposit<N-o>
sprovvedut<N-o>
spudoratezz<N-a>
spumant<N-e>
spunt<N-o>
spy-story<N-non>
squadr<N-a>
squadret<N-ta>
squadrigli<N-a>
squadrism<N-o>
squadris<N-ta>
squadron<N-e>
squalific<N-a>
squallid<N-o>
squallor<N-e>
squal<N-o>
squatter<N-non>
squilibrat<N-o>
squisi<N-ta>
stabilizzator<N-e>
stacc<N-o>
stad<N-io>
staff<N-non>
staffila<N-ta>
stag<N-ione>
stagis<N-ta>
stalinis<N-ta>
stallier<N-e>
stall<N-o>
stallon<N-e>
stambecc<N-o>
stamberg<N-a>
stampant<N-e>
stampell<N-a>
stamperi<N-a>
stanchezz<N-a>
standardizzaz<N-ione>
stanga<N-ta>
stantuff<N-o>
stanzet<N-ta>
stanziament<N-o>
star<N-non>
starnut<N-o>
start-up<N-non>
stas<N-i>
statal<N-e>
static<N-a>
statistic<N-a>
stat<N-o>
statuet<N-ta>
statuin<N-a>
statur<N-a>
statut<N-o>
stazionarie<N-tA>
staz<N-ione>
steccat<N-o>
stellet<N-ta>
stellon<N-e>
stel<N-o>
stendard<N-o>
stenograf<N-o>
stepp<N-a>
stere<N-o>
sterili<N-tA>
sterilizzaz<N-ione>
sterlin<N-a>
stermin<N-io>
steroid<N-e>
sterpagli<N-a>
stess<N-o>
stil<N-e>
stiletta<N-ta>
stilis<N-ta>
still<N-a>
stimolant<N-e>
stimolator<N-e>
stimolaz<N-ione>
stimol<N-o>
stinc<N-o>
stirament<N-o>
stirp<N-e>
stiv<N-a>
stivalon<N-e>
stizz<N-a>
stocca<N-ta>
stol<N-a>
stoltezz<N-a>
stoppa<N-ta>
stordiment<N-o>
storiac<N-cia>
storicis<N-ta>
storiell<N-a>
storiografi<N-a>
stracc<N-io>
strad<N-a>
stradet<N-ta>
stradon<N-e>
stramaledet<N-ta>
strapoter<N-e>
strapp<N-o>
stratosfer<N-a>
stratton<N-e>
straz<N-io>
striatur<N-a>
stridor<N-e>
striglia<N-ta>
strillon<N-e>
stringatezz<N-a>
strip<N-non>
striscia<N-ta>
strisciolin<N-a>
strisc<N-ione>
strizza<N-ta>
strizzatin<N-a>
strof<N-a>
strofet<N-ta>
strofinacc<N-io>
stronza<N-ta>
stronz<N-o>
strumentalism<N-o>
strumentalizzaz<N-ione>
strumentaz<N-ione>
strument<N-o>
strutturalism<N-o>
studentess<N-a>
stuf<N-a>
stupidaggin<N-e>
stupida<N-ta>
stupid<N-o>
stupor<N-e>
sub-appalt<N-o>
sub-continent<N-e>
sub-cultur<N-a>
subacque<N-o>
subdol<N-a>
subentrant<N-e>
subfornitur<N-a>
sublimaz<N-ione>
subordinat<N-o>
suburb<N-io>
success<N-ione>
success<N-o>
succ<N-o>
sud<N-non>
suddet<N-ta>
suddit<N-o>
suffraget<N-ta>
suffrag<N-io>
suggell<N-o>
suggeritor<N-e>
suggestiv<N-o>
sug<N-o>
sultanat<N-o>
sumer<N-o>
sum<N-ma>
summit<N-non>
suocer<N-a>
suol<N-a>
suonator<N-e>
suor<N-a>
super-ispettor<N-e>
superalcolic<N-o>
superb<N-a>
superbanc<N-a>
superb<N-o>
superboll<N-o>
supercalcolator<N-e>
superdollar<N-o>
superdonn<N-a>
superero<N-e>
superespert<N-o>
superficial<N-e>
superfortezz<N-a>
superiori<N-tA>
superkiller<N-non>
superlatitant<N-e>
superlativ<N-o>
superlavor<N-o>
superleg<N-a>
superman<N-non>
supermanager<N-non>
supermarc<N-o>
supermartedì<N-non>
superminim<N-o>
superminister<N-o>
supermodell<N-a>
supermul<N-ta>
superospit<N-e>
superpetrolier<N-a>
superpoliziott<N-o>
superprefett<N-o>
superprocur<N-a>
superproduz<N-ione>
supertecnic<N-o>
supertest<N-e>
supertestimon<N-e>
supertren<N-o>
superuom<N-o>
supervis<N-ione>
suppellettil<N-e>
supplementar<N-e>
supplent<N-e>
suppletiv<N-a>
supponenz<N-a>
support<N-o>
suppos<N-ta>
supremazi<N-a>
surf<N-non>
surfis<N-ta>
surrealis<N-ta>
surrogat<N-o>
sussidiarie<N-tA>
sussidiar<N-io>
sussurr<N-o>
svag<N-o>
svalutaz<N-ione>
svantagg<N-io>
sventaglia<N-ta>
sventrament<N-o>
sventur<N-a>
svincol<N-o>
svizzer<N-a>
svol<N-ta>
svuotament<N-o>
swap<N-non>
swing<N-non>
tabacca<N-io>
tabacchier<N-a>
tabagis<N-ta>
tabellin<N-a>
tabellon<N-e>
taccuin<N-o>
tagik<N-o>
tagli<N-a>
tagliatell<N-a>
tagl<N-ione>
tak<N-e>
tal<N-e>
tallon<N-e>
talp<N-a>
tamburin<N-o>
tampon<N-e>
tanf<N-o>
tangent<N-e>
tang<N-o>
tanker<N-non>
tapparell<N-a>
tapp<N-o>
tar<N-a>
tarantolat<N-o>
tarassac<N-o>
target<N-non>
tariffar<N-io>
tariffaz<N-ione>
tartin<N-a>
tartuf<N-o>
task-forc<N-e>
tassell<N-o>
tassinar<N-o>
tassis<N-ta>
tass<N-o>
tassì<N-non>
tastier<N-a>
tatt<N-o>
tautolo<N-gia>
tavolacc<N-io>
tavolet<N-ta>
tavol<N-o>
tavolozz<N-a>
tax<N-i>
tazeba<N-o>
teatrant<N-e>
teatrin<N-o>
teatr<N-o>
teatrodanz<N-a>
tec<N-a>
tecnocrat<N-e>
tecnolo<N-gia>
tecnostruttur<N-a>
teconolo<N-gia>
tegam<N-e>
teier<N-a>
telecrazi<N-a>
telecronac<N-a>
telecronis<N-ta>
teledipendent<N-e>
telefax<N-non>
telefilm<N-non>
telefona<N-ta>
telefonin<N-o>
telefon<N-o>
telegiornalis<N-ta>
telegram<N-ma>
telelavor<N-o>
telematic<N-a>
telemetri<N-a>
telenovel<N-a>
teleobiettiv<N-o>
teleoperator<N-e>
telepredicator<N-e>
teleselez<N-ione>
televendi<N-ta>
televisor<N-e>
tematic<N-a>
tempism<N-o>
tempistic<N-a>
templ<N-i>
temporanei<N-tA>
temporeggiament<N-o>
tempr<N-a>
tena<N-cia>
tendenziosi<N-tA>
tendin<N-a>
tendinit<N-e>
tendon<N-e>
tendopol<N-i>
tenebr<N-a>
tenent<N-e>
tener<N-o>
tennis<N-non>
tennis<N-ta>
tentator<N-e>
tentennament<N-o>
tenutar<N-io>
tenzon<N-e>
teori<N-a>
teoric<N-o>
tepor<N-e>
teppism<N-o>
teppis<N-ta>
terapi<N-a>
tergicristall<N-o>
tergiversaz<N-ione>
terminal<N-non>
terminal<N-e>
termin<N-e>
terminolo<N-gia>
termita<N-io>
termit<N-e>
terra-ari<N-a>
terrafer<N-ma>
terrestr<N-e>
territor<N-io>
terrorism<N-o>
terroris<N-ta>
terzett<N-o>
terzin<N-a>
terz<N-o>
terzomondis<N-ta>
tesser<N-a>
tessitur<N-a>
test<N-non>
testament<N-o>
testard<N-a>
testard<N-o>
testimonianz<N-a>
testin<N-a>
test<N-o>
tetraggin<N-e>
tetralo<N-gia>
tet<N-ta>
tett<N-o>
teutonic<N-o>
tfr<N-non>
thatcherism<N-o>
thrilling<N-non>
tibi<N-a>
ti<N-e>
tifon<N-e>
tiggì<N-non>
tigl<N-io>
tigr<N-e>
tigì<N-non>
timbr<N-o>
time-out<N-non>
timer<N-non>
timing<N-non>
timpan<N-o>
tinell<N-o>
tintinn<N-io>
tintori<N-a>
tintur<N-a>
tip<N-a>
tip<N-o>
tipograf<N-o>
tir<N-non>
tiragg<N-io>
tirann<N-o>
tirant<N-e>
tirapied<N-i>
tiratur<N-a>
tiriter<N-a>
tir<N-o>
titubant<N-e>
toast<N-non>
toccasan<N-a>
tocchett<N-o>
toilett<N-e>
told<N-a>
tollerabili<N-tA>
tollerant<N-e>
tombarol<N-o>
tombin<N-o>
tom<N-o>
tonali<N-tA>
tond<N-a>
tondin<N-o>
tonic<N-o>
tonnar<N-a>
tonn<N-o>
ton<N-o>
tonsillit<N-e>
top<N-non>
topp<N-a>
torac<N-e>
torbid<N-o>
tord<N-o>
torna<N-ta>
tornein<N-o>
torne<N-o>
tor<N-o>
torpedon<N-e>
torrent<N-e>
torron<N-e>
tortor<N-a>
torturator<N-e>
toscan<N-o>
tossic<N-a>
tossicodipendenz<N-a>
tossicoman<N-e>
tossicomani<N-a>
tossin<N-a>
tot<N-non>
totalitarism<N-o>
tot<N-o>
totocalc<N-io>
totoner<N-o>
tour<N-non>
tovagli<N-a>
township<N-non>
trabocchett<N-o>
traccheggiament<N-o>
trache<N-a>
tracotanz<N-a>
tradiment<N-o>
trading<N-non>
tradit<N-o>
traditor<N-e>
tradizionalism<N-o>
tradiz<N-ione>
traduttric<N-e>
traduz<N-ione>
trafilett<N-o>
tragicommedi<N-a>
train<N-o>
trambust<N-o>
tramont<N-o>
trampolin<N-o>
tramvier<N-e>
tranc<N-e>
tranell<N-o>
tranquilli<N-tA>
transalpin<N-a>
transaz<N-ione>
transenn<N-a>
transessual<N-e>
transfug<N-a>
transiz<N-ione>
transumanz<N-a>
trapass<N-o>
trapezis<N-ta>
trapiantat<N-o>
trapiant<N-o>
trasandatezz<N-a>
trascinator<N-e>
trascriz<N-ione>
trascuratezz<N-a>
trasfer<N-ta>
trasfiguraz<N-ione>
trasformator<N-e>
trasfus<N-ione>
trasgress<N-ione>
traslaz<N-ione>
trasparenz<N-a>
trasportator<N-e>
trasposiz<N-ione>
trasversali<N-tA>
trattament<N-o>
trattat<N-o>
trattenu<N-ta>
tratt<N-o>
trattor<N-e>
trattori<N-a>
travaglia<N-ta>
travas<N-o>
travers<N-a>
traversa<N-ta>
traversi<N-a>
traversin<N-a>
travertin<N-o>
travestitism<N-o>
tre-giorn<N-i>
tregu<N-a>
trekking<N-non>
tremol<N-io>
tremor<N-e>
tren<N-o>
trentennal<N-e>
trentenn<N-e>
trepidaz<N-ione>
trequart<N-i>
trequartis<N-ta>
trespol<N-o>
trevigian<N-o>
triangol<N-o>
tribolaz<N-ione>
tribun<N-a>
tribunet<N-ta>
tributari<N-a>
tributaris<N-ta>
tricicl<N-o>
tricolor<N-e>
tril<N-ione>
trill<N-o>
trini<N-tA>
tr<N-io>
trionfant<N-e>
tripl<N-a>
tripod<N-e>
tripud<N-io>
triumvir<N-o>
trivellaz<N-ione>
trofe<N-o>
trojk<N-a>
trombon<N-e>
trombos<N-i>
trottol<N-a>
trovarobat<N-o>
trovatell<N-o>
trucchett<N-o>
trucc<N-o>
truculenz<N-a>
truff<N-a>
truffator<N-e>
trull<N-o>
tuareg<N-non>
tubercolos<N-i>
tuber<N-o>
tubicin<N-o>
tubin<N-o>
tubolar<N-e>
tulipan<N-o>
tumul<N-o>
turbant<N-e>
turbativ<N-a>
turbin<N-e>
turb<N-o>
turbolenz<N-a>
turcheri<N-a>
turc<N-o>
turgor<N-e>
turibol<N-o>
turis<N-ta>
turn<N-non>
turn-over<N-non>
turnaz<N-ione>
turnis<N-ta>
turn<N-o>
turp<N-e>
turpiloqu<N-io>
tutin<N-a>
tutor<N-e>
tuts<N-i>
ubriacatur<N-a>
ubriac<N-o>
uccellacc<N-io>
uccellin<N-o>
uccis<N-a>
uccisor<N-e>
ucrain<N-o>
uditor<N-e>
uditor<N-io>
ufficial<N-e>
ufficialett<N-o>
ufficiali<N-tA>
ufficializzaz<N-ione>
ugol<N-a>
ulan<N-o>
ulivet<N-o>
ultras<N-non>
ultrasuon<N-o>
ultrà<N-non>
umil<N-e>
umil<N-tA>
umorali<N-tA>
unguent<N-o>
unici<N-tA>
unionis<N-ta>
unison<N-o>
unitarie<N-tA>
untor<N-e>
unz<N-ione>
uomo-radar<N-non>
urbanizzaz<N-ione>
urgenz<N-a>
urn<N-a>
urt<N-o>
uruguayan<N-o>
usanz<N-a>
uscier<N-e>
us<N-o>
ustas<N-cia>
usur<N-a>
utilitari<N-a>
utilizz<N-o>
utopi<N-a>
utopis<N-ta>
uv<N-a>
uzbek<N-o>
vacanz<N-a>
vaghezz<N-a>
vagin<N-a>
vagit<N-o>
vagli<N-a>
vag<N-o>
vagon<N-e>
valdostan<N-o>
valent<N-e>
validi<N-tA>
vallet<N-ta>
vall<N-o>
valtellines<N-e>
valutaz<N-ione>
valvassin<N-o>
valvassor<N-e>
vamp<N-non>
vampir<N-o>
van<N-non>
vancanz<N-a>
vandal<N-o>
vani<N-tA>
vant<N-o>
vaporett<N-o>
variabili<N-tA>
variaz<N-ione>
variegat<N-o>
varie<N-tA>
variopin<N-ta>
var<N-o>
vascell<N-o>
vascon<N-e>
vasett<N-o>
vassall<N-o>
vasso<N-io>
vasti<N-tA>
vat<N-e>
vecchiai<N-a>
vecchiet<N-ta>
vecchiezz<N-a>
vecchin<N-a>
vecch<N-io>
vecch<N-ione>
vedovanz<N-a>
vedu<N-ta>
vegetarian<N-o>
veggent<N-e>
vegli<N-a>
vegliard<N-o>
veicol<N-o>
vel<N-a>
vela<N-io>
velar<N-io>
velatur<N-a>
velen<N-o>
velin<N-a>
velis<N-ta>
vell<N-o>
velocis<N-ta>
veloci<N-tA>
velodrom<N-o>
ven<N-a>
venatur<N-a>
vendemmi<N-a>
vendet<N-ta>
vendi<N-ta>
venditor<N-e>
venditric<N-e>
venerat<N-o>
veneraz<N-ione>
venerdì<N-non>
venezian<N-a>
venezian<N-o>
venezuelan<N-o>
ventagl<N-io>
venta<N-ta>
ventennal<N-e>
ventenn<N-io>
ventiseienn<N-e>
vent<N-o>
ventunenn<N-e>
ventur<N-a>
ventur<N-e>
verbal<N-e>
verb<N-o>
verd<N-e>
vergin<N-e>
vergogn<N-a>
verific<N-a>
verones<N-e>
veronic<N-a>
verricell<N-o>
versament<N-o>
vers<N-ione>
verticali<N-tA>
verticalizzaz<N-ione>
vescov<N-o>
vesp<N-a>
vespa<N-io>
vessill<N-o>
vestagli<N-a>
vestal<N-e>
vest<N-e>
vestiar<N-io>
vestibol<N-o>
vesti<N-gia>
vesti<N-ta>
vestiz<N-ione>
veteran<N-a>
veteran<N-o>
vet<N-o>
vetrin<N-o>
vettur<N-a>
viados<N-non>
vial<N-e>
vialett<N-o>
vibrat<N-o>
vice-cap<N-o>
vice-premier<N-non>
vice-president<N-e>
vicebrigadier<N-e>
vicecancellier<N-e>
vicecap<N-o>
vicecapogrupp<N-o>
viceconsol<N-e>
viceministr<N-o>
vicepremier<N-non>
viceprocurator<N-e>
vicequestor<N-e>
vicinanz<N-a>
video-casset<N-ta>
video-gam<N-e>
video-gioc<N-o>
videocasset<N-ta>
videocrazi<N-a>
videodisc<N-o>
videogam<N-e>
videonastr<N-o>
videopoker<N-non>
videoregistraz<N-ione>
videotap<N-e>
videotec<N-a>
vietnami<N-ta>
vigilantes<N-non>
vigilanz<N-a>
vigilat<N-o>
vigil<N-e>
vigiless<N-a>
vigliaccheri<N-a>
vigliacc<N-o>
vign<N-a>
viking<N-non>
vilipend<N-io>
vill<N-a>
villagg<N-io>
villanell<N-a>
villani<N-a>
villan<N-o>
villeggiatur<N-a>
vil<N-tA>
vilupp<N-o>
vincent<N-e>
vincol<N-o>
violator<N-e>
violentator<N-e>
violenz<N-a>
violin<N-o>
violoncellis<N-ta>
viottol<N-o>
virag<N-o>
virgol<N-a>
virgolettat<N-o>
virgult<N-o>
virolog<N-o>
virtuosism<N-o>
vis<N-non>
visin<N-o>
vis<N-ione>
visita-lamp<N-o>
visitatric<N-e>
vis<N-o>
vissu<N-ta>
vist<N-o>
visualizzaz<N-ione>
visur<N-a>
vi<N-ta>
vitalism<N-o>
vitali<N-tA>
vitamin<N-a>
vitell<N-o>
viticoltor<N-e>
vitt<N-o>
vittorios<N-o>
vituperat<N-o>
viuzz<N-a>
vivais<N-ta>
viver<N-o>
viz<N-io>
vizios<N-o>
vocabol<N-o>
vocalist<N-non>
vocalis<N-ta>
vocali<N-tA>
vocalizz<N-o>
voc<N-ione>
vodk<N-a>
vogator<N-e>
vogli<N-a>
volan<N-o>
volant<N-e>
volantinagg<N-io>
voler<N-e>
volgari<N-tA>
volgarizzaz<N-ione>
volier<N-a>
vol<N-o>
volontari<N-a>
volontariat<N-o>
volontarie<N-tA>
volontar<N-io>
volon<N-tA>
volp<N-e>
volé<N-e>
vomit<N-o>
von<N-non>
voraci<N-tA>
voragin<N-e>
vortic<N-e>
votaz<N-ione>
vox<N-non>
voyeurism<N-o>
vulcan<N-o>
vulcanolog<N-o>
vulnerabili<N-tA>
vulnus<N-non>
watuss<N-o>
wc<N-non>
week-end<N-non>
whisky<N-non>
won<N-non>
workstation<N-non>
xenofobi<N-a>
yacht<N-non>
yogurt<N-non>
yur<N-ta>
zain<N-o>
zaires<N-e>
zamp<N-a>
zampa<N-ta>
zampill<N-o>
zampin<N-o>
zann<N-a>
zanzar<N-a>
zapp<N-a>
zarin<N-a>
zavorr<N-a>
zecc<N-a>
zi<N-a>
zig-zag<N-non>
zigom<N-o>
zingar<N-a>
zingarell<N-a>
zingar<N-o>
z<N-io>
zitell<N-a>
zoll<N-a>
zomb<N-i>
zombi<N-e>
zonis<N-ta>
zoom<N-non>
zuccherific<N-io>
àncor<N-a>
